@echo off

echo # generated by automake
echo+

for /F "delims=;" %%I in (makefile.win) do set %%I

if not exist %OUTDIR% mkdir %OUTDIR%
set OFILES=%CFILES:.c=.o% %CPPFILES:.cpp=.o%
set ALL=
for %%I in (%TARGETS%) do set ALL=%ALL% %OUTDIR%\%%I

echo all: %ALL%
echo+ 

echo clean:
echo+	del %OUTDIR%\%TARGETS% %OUTDIR%\%OFILES%
echo+

for %%I in (%TARGETS%) do (call :link %OUTDIR%\%%I)

for %%I in (%CFILES%) do call :c %%~nI
for %%I in (%CPPFILES%) do call :cpp %%~nI

goto :EOF

:c
set file=%1%
echo %file%.o: %file%.c
echo+	%gcc% %CFLAGS% -c %file%.c -o %file%.o
echo+ 
goto :EOF

:cpp
set file=%1%
echo %file%.o: %file%.cpp
echo+	%gcc% %CPPFLAGS% -c %file%.cpp -o %file%.o
echo+ 

goto :EOF

:link
set file=%*%
echo %file%: %OFILES% 
echo+	%gcc% %LFLAGS% %OFILES% -o %file% 
echo+ 

goto :EOF