#!/bin/bash
# $Id: compare-sources,v 1.4 2007/10/21 19:15:53 d3g637 Exp $
# Copyright (C) 2008 Battelle Memorial Institute
# This file is distributed under the same terms as GridLAB-D.
# Script for comparing source files listed in automake templates (Makefile.am)
# and Visual Studio 2005 project files.  Usage: ./compare-sources MODULES...

# Echo the first argument
function getitem() {
	echo $1
}

# Echo all arguments but the first
function shiftlist() {
	shift 1
	echo $*
}

function diffitems() {
	LIST1=$1
	LIST2=$2
	while [[ $LIST1 ]] && [[ $LIST2 ]]; do
		ITEM1=`getitem $LIST1`
		ITEM2=`getitem $LIST2`
		if [[ $ITEM1 != $ITEM2 ]]; then
			echo "    $ITEM2"
		else
			LIST1=`shiftlist $LIST1`
		fi
		LIST2=`shiftlist $LIST2`
	done
	for ITEM2 in $LIST2; do
		echo "    $ITEM2"
	done
}

function diffmodule() {
	# VS project sources
	VS_FILES=`grep '^\s*RelativePath=".*\.\(c\|h\)\(pp\)\?"\s*$' VS2005/$1.vcproj | sed -e 's/^.*"\(.*\)".*$/\1/' -e 's/\\\\/\\//g' -e "s/^..\/$1\///" | sort -u | xargs`

	# makefile sources
	MAKE_FILES=`grep '^\s*\(.*_SOURCES\s*=\s*\)\?[^[:space:]]\+\.\(c\|h\)\(pp\)\?\s*\\\\\?' $1/Makefile.am | sed -e 's/^\s*\(\S*\)\s*\\\\\?/\1/' | sort -u | xargs`

	if [[ "$VS_FILES" == "$MAKE_FILES" ]]; then
		echo Source files match: $1
	else
		echo Source files do not match: $1
		ALL_FILES=`echo $VS_FILES $MAKE_FILES | sed 's/\s\+/\n/g' | sort -u | xargs`
		if [[ "$MAKE_FILES" != "$ALL_FILES" ]]; then
			echo Only in $1.vcproj:
			diffitems "$MAKE_FILES" "$ALL_FILES"
		fi
		if [[ "$VS_FILES" != "$ALL_FILES" ]]; then
			echo Only in $1/Makefile.am:
			diffitems "$VS_FILES" "$ALL_FILES"
		fi
		return 1
	fi
}

if (( ! $# )); then
	echo "Usage: $0 MODULE..."
	exit 1
fi

FAILED=0
for MODULE in $*; do
	MODULE=`echo $MODULE | sed -e 's/\(^\s*\)\|\(\/\s*\$\)//g'`
	if [ ! -d ./$MODULE ]; then
		echo $0: No such module: $MODULE
		FAILED=$(($FAILED + 1))
	else
		diffmodule $MODULE
		if (( $? != 0 )); then FAILED=$((FAILED + 1)); fi
	fi
done

exit $FAILED

