site_name: GridLAB-D Documentation
theme:
  name: readthedocs
  highlightjs: true
  display_version: false
  style_external_links: true
  logo: images/logo.png
  user_color_mode_toggle:  true
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - mkdoxy:
      projects:
       gridlabd:
          src-dirs: assert autotest build climate comm commercial connection control debug generators gldcore GldEditor market matlab matpower mysql network optimize plc powerflow python reliability residential rest tape tape_file tape_memory tape_plot utitlies
          full-doc: True 
          doxy-cfg: 
            FILE_PATTERNS: "*.cpp *.h*" 
            RECURSIVE: True 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown_include.include:
      base_path: docs/
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - admonition
  - codehilite
nav:
  - Home: index.md
  - 0.0 - GridLAB-D™:
    - Introduction: docs/0.0 - GridLAB-D™/0.1 - Introduction.md
    - Resources & Support: docs/0.0 - GridLAB-D™/0.2 - resources.md
    - Publications: docs/0.0 - GridLAB-D™/0.3 - publications.md
    - Projects: docs/0.0 - GridLAB-D™/0.4 - projects.md
    - Version History: docs/0.0 - GridLAB-D™/0.5 - Version History.md
    - Contact: docs/0.0 - GridLAB-D™/0.6 - Contacts_list.md
    - Style Guide: docs/0.0 - GridLAB-D™/style-guide.md
  - 1.0 - Prospective Users:
    - Key Attributes of GridLAB-D™: docs/1.0 - Prospective Users/GridLAB-D_Key_Attributes.md
    - Technical Overview: docs/1.0 - Prospective Users/Technical_Overview.md
  - 2.0 - New Users:
    - Quick Install: docs/2.0 - New Users/2.1 - Installation Guide.md
    - 2.2 - Getting Started:
      - Gridlab-D™ Overview: docs/2.0 - New Users/2.2 - Getting Started/2.2.1 - Overview.md
      - What is a GridLAB-D™ Model?: docs/2.0 - New Users/2.2 - Getting Started/2.2.2 - Models.md
      - Running GridLAB-D™: docs/2.0 - New Users/2.2 - Getting Started/2.2.3 - Running a Model.md
      - Generating populations: docs/2.0 - New Users/2.2 - Getting Started/2.2.5 - Model Options.md
      - Generating output: docs/2.0 - New Users/2.2 - Getting Started/2.2.6 - Output.md
    - 2.3 - Running Simulations: docs/2.0 - New Users/2.3 - Running_Simulations.md
    - 2.5 - Intro to Modeling:
      - Basic Distribution System Modeling: docs/2.0 - New Users/2.5 - Intro to Modeling/2.5.1 - Basic Distribution System Modeling.md
      - GLM Models: docs/2.0 - New Users/2.5 - Intro to Modeling/2.5.2 - GLM Models.md
      - Modules: docs/2.0 - New Users/2.5 - Intro to Modeling/2.5.3 - Modules.md
      - Recorders and Players: docs/2.0 - New Users/2.5 - Intro to Modeling/2.5.4 - Recorders and Players.md
      - Built-in Schedules and Loadshapes: docs/2.0 - New Users/2.5 - Intro to Modeling/2.5.5 - Schedules and Loadshapes.md
      - Distributed Generation: docs/2.0 - New Users/2.5 - Intro to Modeling/2.5.6 - Distributed_Generation.md
      - Advanced Distribution Models: docs/2.0 - New Users/2.5 - Intro to Modeling/2.5.7 - Advanced_Distribution_Models.md
      - Built-In Distribution Models: docs/2.0 - New Users/2.5 - Intro to Modeling/2.5.8 - Built-In Distribution Models.md
    - The Clock: docs/2.0 - New Users/2.5 - Simulation Time.md
  - 3.0 - Modeling Reference:
    - Loads:
      - Loadshape: docs/3.0 - Modeling Reference/Loads/1.0 - Loadshape.md
      - Load Composition: docs/3.0 - Modeling Reference/Loads/2.0 - Load_Composition.md
      - Industrial and Agricultural Loads: docs/3.0 - Modeling Reference/Loads/3.0 - Industrial_and_agricultural_loads.md
    - Metrics & Recorders:
      - Recorder: docs/3.0 - Modeling Reference/Metrics & Recorders/1.0 - Recorder.md
      - Multi recorder: docs/3.0 - Modeling Reference/Metrics & Recorders/2.0 - Multi_recorder.md
      - Metrics collector: docs/3.0 - Modeling Reference/Metrics & Recorders/3.0 - Metrics_collector.md
      - Metrics collector writer: docs/3.0 - Modeling Reference/Metrics & Recorders/4.0 - Metrics_collector_writer.md
      - Plotting Output: docs/3.0 - Modeling Reference/Metrics & Recorders/plotting-output.md
    - Modules:
      - Introduction: docs/3.0 - Modeling Reference/Modules/1.0 - Introduction.md
      - Assert: docs/3.0 - Modeling Reference/Modules/Assert.md
      - Climate:
        - Climate Module: docs/3.0 - Modeling Reference/Modules/Climate/1.0 - Climate.md
        - CSV reader: docs/3.0 - Modeling Reference/Modules/Climate/CSV_reader_(climate_class).md
      - Generators:
        - Diesel dg: docs/3.0 - Modeling Reference/Modules/Generators/Diesel_dg.md
        - Battery Energy storage: docs/3.0 - Modeling Reference/Modules/Generators/Energy_storage.md
        - Inverters:
          - Inverter: docs/3.0 - Modeling Reference/Modules/Generators/Inverters/Inverter.md
          - ibr blackboxmodels: docs/3.0 - Modeling Reference/Modules/Generators/Inverters/Spec_ibr_blackboxmodels.md
          - ibr grayboxmodels: docs/3.0 - Modeling Reference/Modules/Generators/Inverters/Spec_ibr_grayboxmodels.md
          - inverter_dyn: docs/3.0 - Modeling Reference/Modules/Generators/Inverters/Spec_inverter_dyn.md
          - Sec control: docs/3.0 - Modeling Reference/Modules/Generators/Inverters/Spec_sec_control.md
          - Sync Ctrl: docs/3.0 - Modeling Reference/Modules/Generators/Inverters/Spec_sync_ctrl.md
          - Voltage source inverter (VSI): docs/3.0 - Modeling Reference/Modules/Generators/Inverters/Voltage_source_inverter_(VSI).md
        - Solar Panel: docs/3.0 - Modeling Reference/Modules/Generators/Solar.md
        - Wind Turbine: docs/3.0 - Modeling Reference/Modules/Generators/Windturb_dg.md
      - Powerflow:
        - Power Flow User Guide: docs/3.0 - Modeling Reference/Modules/Powerflow/1.0 - Power_Flow_User_Guide.md
        - Powerflow Tehnical Reference: docs/3.0 - Modeling Reference/Modules/Powerflow/3.0 - Power_Flow_Reference.md
        - Reliability User Guide: docs/3.0 - Modeling Reference/Modules/Powerflow/4.0 - Reliability_User_Guide.md
        - Newton-Raphson Distribution Powerflow Solver: docs/3.0 - Modeling Reference/Modules/Powerflow/5.0 - Newton-Raphson_Distribution_Powerflow_Solver.md
        - Motor:
          - Composition Motor: docs/3.0 - Modeling Reference/Modules/Powerflow/Motor/Tech_CompositionMotor.md
          - Single Phase Induction Motors: docs/3.0 - Modeling Reference/Modules/Powerflow/Motor/Tech_DeltaSPIM.md
          - Three Phase Induction Motors: docs/3.0 - Modeling Reference/Modules/Powerflow/Motor/Tech_DeltaTPIM.md
        - Series compensator: docs/3.0 - Modeling Reference/Modules/Powerflow/Series_compensator.md
        - Switch: docs/3.0 - Modeling Reference/Modules/Powerflow/Switch_object.md
      - Residential:
        - Introduction: docs/3.0 - Modeling Reference/Modules/Residential/1.0 - Introduction.md
        - House: docs/3.0 - Modeling Reference/Modules/Residential/2.0 - house-e.md
        - Equivalent Thermal Parameter Model: docs/3.0 - Modeling Reference/Modules/Residential/ETP_closed_form_solution.md
        - Evcharger det: docs/3.0 - Modeling Reference/Modules/Residential/Evcharger_det.md
        - End Use Loads: docs/3.0 - Modeling Reference/Modules/Residential/Loads.md
        - Thermal Energy Storage Model: docs/3.0 - Modeling Reference/Modules/Residential/Thermal_Energy_Storage_model_guide.md
        - Waterheater: docs/3.0 - Modeling Reference/Modules/Residential/Waterheater.md
        - ZIPload: docs/3.0 - Modeling Reference/Modules/Residential/ZIPload.md
      - Tape:
        - Player: docs/3.0 - Modeling Reference/Modules/Tape/Player.md
        - Tape: docs/3.0 - Modeling Reference/Modules/Tape/Tape.md
      - Delta Mode Document: docs/3.0 - Modeling Reference/Modules/delta_mode.md
    - Other Features:
      - Checkpoints: docs/3.0 - Modeling Reference/Other Features/Checkpoints.md
      - Command Options: docs/3.0 - Modeling Reference/Other Features/Command_options.md
      - Microgrids: docs/3.0 - Modeling Reference/Other Features/Microgrids.md
      - Performance profiling: docs/3.0 - Modeling Reference/Other Features/Performance_profiling.md
      - Sync Check: docs/3.0 - Modeling Reference/Other Features/Spec_sync_check.md
      - Units: docs/3.0 - Modeling Reference/Other Features/Units.md
      - Validate: docs/3.0 - Modeling Reference/Other Features/Validate.md
  - 4.0 Developing Reference:
    - 4.0 - Feature Development:
      - Basic C/C++ API: docs/4.0 Developing Reference/4.0 - Feature Development/Basic C-C++ API.md
      - Checkpointing: docs/4.0 Developing Reference/4.0 - Feature Development/Checkpointing.md
      - Docker Containerization: docs/4.0 Developing Reference/4.0 - Feature Development/Docker Containerization.md
      - JSON Loader: docs/4.0 Developing Reference/4.0 - Feature Development/JSON Loader.md
      - Multithreading: docs/4.0 Developing Reference/4.0 - Feature Development/Multithreading.md
      - Stretch Goals: docs/4.0 Developing Reference/4.0 - Feature Development/Stretch Goals.md
    - 4.1 - Introduction - TBD: docs/4.0 Developing Reference/4.1 - Introduction.md
    - 4.2 - Building from Source:
      - 4.2 - Building GridLAB-D™ from Source: docs/4.0 Developing Reference/4.2 - Building from Source/4.2.1 - Building_from_Source.md
      - Setting-Up MSYS2 for Windows: docs/4.0 Developing Reference/4.2 - Building from Source/4.2.2 - Setting-Up_MSYS2_for_Windows.md
      - Setting-Up WSL for Windows: docs/4.0 Developing Reference/4.2 - Building from Source/4.2.3 - Setting-Up_WSL_for_Windows.md
      - Setting-Up the VS Code IDE: docs/4.0 Developing Reference/4.2 - Building from Source/4.2.4 - Setting-Up_VS_Code.md
      - Dev:mysql: docs/4.0 Developing Reference/4.2 - Building from Source/4.2.5 - Building with mysql.md
    - 4.3 - Software Architecture and Design:
      - Introduction - TBD: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.0 - Introduction.md
      - gldcore: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.1 - gldcore.md
      - Powerflow External LU Solver Interface: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.10 - Powerflow_External_LU_Solver_Interface.md
      - GridLAB-D™ Modules: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.2 - Modules.md
      - GridLAB-D™ Objects: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.3 - Objects.md
      - Object Synchronization Process: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.4 - Object Synchronization Process.md
      - GridLAB-D™ Parallelization: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.6 - Parallelization.md
      - GridLAB-D™ Loader: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.7 - Loader.md
      - GridLAB-D™ Data Transforms: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.8 - Transforms.md
      - libgld: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/4.3.9 - libgld.md
      - Spec:Initialization: docs/4.0 Developing Reference/4.3 - Software Architecture and Design/Spec_Initialization.md
    - 4.4 - Development Fundamentals:
      - Programming conventions: docs/4.0 Developing Reference/4.4 - Development Fundamentals/4.4.1 - Programming_conventions.md
      - Creating a module - v1: docs/4.0 Developing Reference/4.4 - Development Fundamentals/4.4.2 - Creating_a_module.md
      - Creating a class: docs/4.0 Developing Reference/4.4 - Development Fundamentals/4.4.3 - Creating_a_class.md
      - Creating a solver: docs/4.0 Developing Reference/4.4 - Development Fundamentals/4.4.4 - Creating_a_solver.md
      - GridLAB-D™ Device Modeling: docs/4.0 Developing Reference/4.4 - Development Fundamentals/4.4.5 - GridLAB-D Device Modeling.md
      - Integrated Testing: docs/4.0 Developing Reference/4.4 - Development Fundamentals/4.4.6 - Integrated_Testing.md
    - 4.5 - Deltamode Development:
      - Introduction to Deltamode Development - TBD: docs/4.0 Developing Reference/4.5 - Deltamode Development/4.5.0 - Introduction to Deltamode Development.md
      - Dev:Subsecond: docs/4.0 Developing Reference/4.5 - Deltamode Development/4.5.1 - Dev_Subsecond.md
      - Subsecond: docs/4.0 Developing Reference/4.5 - Deltamode Development/Delta_mode.md
      - Model Initialization: docs/4.0 Developing Reference/4.5 - Deltamode Development/Initialization.md
      - Multirun mode: docs/4.0 Developing Reference/4.5 - Deltamode Development/Multirun_mode.md
      - Multithreaded Random Number Generation: docs/4.0 Developing Reference/4.5 - Deltamode Development/Multithreaded_Random_Number_Generation.md
      - Pauseat: docs/4.0 Developing Reference/4.5 - Deltamode Development/Pauseat.md
      - Realtime server: docs/4.0 Developing Reference/4.5 - Deltamode Development/Realtime_server.md
      - Spec:Subsecond: docs/4.0 Developing Reference/4.5 - Deltamode Development/Spec_Subsecond.md
      - 2.4 - Theory of Operation: docs/4.0 Developing Reference/4.5 - Deltamode Development/theory-of-operation.md
    - 4.6 - Debugging:
      - Introduction to Debugging when Developing GridLAB-Debugging: docs/4.0 Developing Reference/4.6 - Debugging/4.6.0 - Introduction.md
      - Command options: docs/4.0 Developing Reference/4.6 - Debugging/4.6.1 - Command_line_arguments.md
      - Performance Profiling: docs/4.0 Developing Reference/4.6 - Debugging/4.6.2 - performance-profiling.md
    - 4.7 - Style Guide: docs/4.0 Developing Reference/4.7 - Style_guide.md
    - GridLAB-D Release Process - TBD: docs/4.0 Developing Reference/4.8 - Release_Process.md
  - 5.0 Integration:
    - Interfacing with External Software: docs/5.0 Integration/Interfacing_with_External_Software.md
    - Intro to Integration: docs/5.0 Integration/intro-to-integration.md
  - 6.0 Examples:
    - Placeholder: docs/6.0 Examples/placeholder.md
  - 7.0 References:
    - Unimplemented:
      - Introduction: docs/7.0 References/Unimplemented/1.0 - Introduction.md
      - Aggregate Demand Response Model: docs/7.0 References/Unimplemented/Aggregate_demand_response_model.md
      - Commercial:
        - Commercial Module: docs/7.0 References/Unimplemented/Commercial/1.0 - Tech_Commercial.md
        - Commercial User Guide: docs/7.0 References/Unimplemented/Commercial/Commercial_User_Guide.md
      - Connection:
        - Connection: docs/7.0 References/Unimplemented/Connection/1.0 - Connection.md
        - fncs msg: docs/7.0 References/Unimplemented/Connection/Connection_fncs_msg.md
        - helics msg: docs/7.0 References/Unimplemented/Connection/Connection_helics_msg.md
        - json: docs/7.0 References/Unimplemented/Connection/Connection_json.md
        - link: docs/7.0 References/Unimplemented/Connection/Connection_link.md
        - security: docs/7.0 References/Unimplemented/Connection/Connection_security.md
        - xml: docs/7.0 References/Unimplemented/Connection/Connection_xml.md
      - End Use Loads:
        - Residential End Uses: docs/7.0 References/Unimplemented/End Use Loads/1.0 - Residential_End_Use.md
        - Hybrid Electric Vehicle Chargers: docs/7.0 References/Unimplemented/End Use Loads/Hybrid_Electric_Vehicle_Chargers.md
        - Lights: docs/7.0 References/Unimplemented/End Use Loads/Lights.md
        - Microwave: docs/7.0 References/Unimplemented/End Use Loads/Microwave.md
        - Range: docs/7.0 References/Unimplemented/End Use Loads/Range.md
        - Refrigerator: docs/7.0 References/Unimplemented/End Use Loads/Refrigerator.md
        - Spec:Dishwasher: docs/7.0 References/Unimplemented/End Use Loads/Spec_Dishwasher.md
        - Spec:Range: docs/7.0 References/Unimplemented/End Use Loads/Spec_Range.md
      - Link:
        - Link (directive): docs/7.0 References/Unimplemented/Link/Link_(directive).md
        - Matlab link: docs/7.0 References/Unimplemented/Link/Matlab_link.md
      - Macros: docs/7.0 References/Unimplemented/Macros.md
      - Market:
        - Market User Guide: docs/7.0 References/Unimplemented/Market/1.0 - Market_User_Guide.md
        - Market Auction: docs/7.0 References/Unimplemented/Market/Market_Auction.md
        - Transactive Controller: docs/7.0 References/Unimplemented/Market/TransactiveController.md
      - Model Debugging: docs/7.0 References/Unimplemented/Model_Debugging.md
      - MySQL:
        - Mysql: docs/7.0 References/Unimplemented/MySQL/Mysql#username.md
        - Database: docs/7.0 References/Unimplemented/MySQL/Database.md
        - HowTo:mysql: docs/7.0 References/Unimplemented/MySQL/HowTo_mysql.md
        - MySQL Import/Export: docs/7.0 References/Unimplemented/MySQL/MySQL_Import_Export.md
        - Player (mysql): docs/7.0 References/Unimplemented/MySQL/Player_(mysql).md
        - Recorder (mysql): docs/7.0 References/Unimplemented/MySQL/Recorder_(mysql).md
      - Network:
        - Network: docs/7.0 References/Unimplemented/Network/Network_Flow_Solver.md
        - Network Flow Guide: docs/7.0 References/Unimplemented/Network/Network_Flow_Guide.md
        - Transmission: docs/7.0 References/Unimplemented/Network/TDIntegration.md
      - Neutral Earth Voltage:
        - Neutral Earth Voltage (NEV): docs/7.0 References/Unimplemented/Neutral Earth Voltage/NEV.md
        - Introduction: docs/7.0 References/Unimplemented/Neutral Earth Voltage/Spec_NEV.md
        - Spec:NEVArray: docs/7.0 References/Unimplemented/Neutral Earth Voltage/Spec_NEVArray.md
        - Spec:NEVDataFormat: docs/7.0 References/Unimplemented/Neutral Earth Voltage/Spec_NEVDataFormat.md
        - Spec:NEVLink: docs/7.0 References/Unimplemented/Neutral Earth Voltage/Spec_NEVLink.md
        - Spec:NEVModules: docs/7.0 References/Unimplemented/Neutral Earth Voltage/Spec_NEVModules.md
        - Spec:NEVNode: docs/7.0 References/Unimplemented/Neutral Earth Voltage/Spec_NEVNode.md
        - Spec:NEVSolver: docs/7.0 References/Unimplemented/Neutral Earth Voltage/Spec_NEVSolver.md
      - Transmission: docs/7.0 References/Unimplemented/Transmission.md
  - reference:
    - ReadMeConfig:
      - authentication: reference/ReadMeConfig/authentication.md
      - getting-started: reference/ReadMeConfig/getting-started.md
      - my-requests: reference/ReadMeConfig/my-requests.md
    - Doxygen: 
        - Groups: gridlabd/group__index.md
        - Structs: gridlabd/structs__index.md
        - Files: gridlabd/files.md
        - Classes: gridlabd/classes.md
        - Hierarchy: gridlabd/hierarchy.md
        - Modules: gridlabd/modules.md
        - Pages: gridlabd/pages.md