#!/usr/bin/env python3
"""
GridLAB-D Checkpoint Validation Script

Runs all autotests through a 4-step checkpoint process:
1. Baseline run
2. Partial run with checkpoint (1 timestep)
3. Restore from checkpoint
4. Compare results

Usage:
    python3 validate_checkpoint.py [-m MODULE] [-t THREADS] [-o] [--keep-checkpoints] [--verbose]
"""

from argparse import ArgumentParser
from pathlib import Path
import math
import multiprocessing
import shutil
import subprocess
import sys
import time
import os
import json
import re
import zlib

# Global state
autotestFiles = []
gldBinary = None
testGldApiBinary = None

PERFECT_PERCENT_THRESHOLD = 5.0
ACCEPTABLE_PERCENT_THRESHOLD = 10.0
MIN_COMPARE_MAGNITUDE = 1e-6
MAX_MISMATCH_DETAILS = 20

COMPLEX_VALUE_PATTERN = re.compile(
    r"^\s*(?P<real>[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*"
    r"(?P<imag_sign>[+-])\s*(?P<imag>(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*"
    r"(?P<imag_unit>[ijIJ])(?:\s+(?P<suffix>.*))?$"
)

IGNORED_CHECKPOINT_PATH_PREFIXES = (
    "$.clock",
)

IGNORED_CHECKPOINT_FIELD_NAMES = {
    "checkpoint_loaded",
    "randomseed",
    "rng_state",
}

IGNORED_CHECKPOINT_PATHS = {
    "$.__preamble.comments[1]",
}

#Autotests to explicitly exclude from checkpointing
excludeTests = ["test_cloud_tmy2_converted", "test_cloud_tmy3_converted"]

def cleanup_test_artifacts(test_dir: Path, test_stem: str) -> None:
    """Remove checkpoint files generated by test_gldapi from a test working directory."""
    artifact_names = {
        f"{test_stem}_full_checkpoint.json",
        f"{test_stem}_partial_checkpoint.json",
        f"{test_stem}_restored_checkpoint.json",
        f"{test_stem}_checkpoint.json",
        "_checkpoint.json",
    }

    for artifact_name in artifact_names:
        artifact_path = test_dir / artifact_name
        if artifact_path.exists() and artifact_path.is_file():
            artifact_path.unlink()


def run_process(command: list[str], cwd: Path, env: dict, timeout: int, capture_output: bool):
    """Run a subprocess with fast success-path defaults and optional output capture."""
    if capture_output:
        return subprocess.run(
            command,
            cwd=cwd,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    return subprocess.run(
        command,
        cwd=cwd,
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        timeout=timeout,
        text=True,
    )


def build_gld_environment() -> dict:
    """Build the GridLAB-D runtime environment used by the launch profiles."""
    env = os.environ.copy()

    if testGldApiBinary:
        build_dir = str(Path(testGldApiBinary).resolve().parent.parent)
    else:
        build_dir = str((Path(__file__).parent / "build").resolve())

    build_bin = os.path.join(build_dir, "bin")
    build_lib = os.path.join(build_dir, "lib")
    build_share = os.path.join(build_dir, "share")
    path_sep = os.pathsep

    env["PATH"] = build_bin + path_sep + env.get("PATH", "")
    env["LD_LIBRARY_PATH"] = build_lib + path_sep + env.get("LD_LIBRARY_PATH", "")
    env["GLPATH"] = path_sep.join([build_lib, build_share, build_dir])
    env["GRIDLABD_HOME"] = build_dir
    return env

class TestResult:
    """Encapsulates the result of a checkpoint test"""
    
    def __init__(self, test_file: Path):
        self.test_file = test_file
        self.skipped = False
        self.skip_reason = ""
        self.step_failed = None  # Which step failed (1-4)
        self.error_message = ""
        self.differences = None  # Number of failed parameter comparisons (None if didn't reach Step 4)
        self.perfect_occurrences = 0
        self.acceptable_occurrences = 0
        self.failed_occurrences = 0
        self.numeric_failed_occurrences = 0
        self.exact_failed_occurrences = 0
        self.total_occurrences = 0
        self.details = {}
        
    def __repr__(self):
        if self.skipped:
            if self.skip_reason:
                return f"[SKIPPED] {self.test_file.name} - {self.skip_reason}"
            return f"[SKIPPED] {self.test_file.name}"
        if self.step_failed:
            msg = f"[INCOMPLETE] {self.test_file.name}"
            if self.step_failed:
                msg += f" - Failed at Step {self.step_failed}"
            if self.error_message:
                msg += f": {self.error_message}"
            return msg
        elif self.total_occurrences > 0:
            if self.failed_occurrences > 0:
                return f"[{self.failed_occurrences} failures] {self.test_file.name}"
            if self.acceptable_occurrences > 0:
                return f"[{self.acceptable_occurrences} acceptable] {self.test_file.name}"
            return f"[perfect] {self.test_file.name}"
        elif self.differences is not None:
            return f"[{self.differences} differences] {self.test_file.name}"
        else:
            return f"[ERROR] {self.test_file.name} - No comparison data"


def is_numeric_value(value) -> bool:
    """Return True for numeric values except booleans."""
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def classify_percent_difference(expected: float, actual: float) -> tuple[str, float]:
    """Classify relative difference between two numeric values."""
    if math.isnan(expected) and math.isnan(actual):
        return "perfect", 0.0

    if math.isnan(expected) or math.isnan(actual):
        return "failed", float("inf")

    if math.isinf(expected) or math.isinf(actual):
        if expected == actual:
            return "perfect", 0.0
        return "failed", float("inf")

    denom = max(abs(expected), abs(actual))
    if denom == 0.0:
        percent_diff = 0.0 if expected == actual else float("inf")
    else:
        percent_diff = (abs(expected - actual) / denom) * 100.0

    if percent_diff <= PERFECT_PERCENT_THRESHOLD:
        return "perfect", percent_diff
    if percent_diff <= ACCEPTABLE_PERCENT_THRESHOLD:
        return "acceptable", percent_diff
    return "failed", percent_diff


def parse_complex_string_magnitude(value: str):
    """Extract complex magnitude and non-numeric suffix from a complex-like string."""
    match = COMPLEX_VALUE_PATTERN.match(value)
    if not match:
        return None

    real = float(match.group("real"))
    imag_sign = -1.0 if match.group("imag_sign") == "-" else 1.0
    imag = imag_sign * float(match.group("imag"))
    suffix = (match.group("suffix") or "").strip()
    magnitude = math.hypot(real, imag)
    return magnitude, suffix


def record_mismatch(summary: dict, path: str, reason: str, expected, actual) -> None:
    """Record a failed occurrence and keep bounded detail samples for reporting."""
    summary["failed"] += 1
    summary["total"] += 1

    if reason in {
        "double differs by more than 10%",
        "complex magnitude differs by more than 10%",
    }:
        summary["numeric_failed"] += 1
    else:
        summary["exact_failed"] += 1

    if len(summary["mismatch_samples"]) < MAX_MISMATCH_DETAILS:
        summary["mismatch_samples"].append(
            {
                "path": path,
                "reason": reason,
                "expected": expected,
                "actual": actual,
            }
        )


def record_occurrence(summary: dict, classification: str) -> None:
    """Increment comparison occurrence counters by classification."""
    summary[classification] += 1
    summary["total"] += 1


def should_skip_checkpoint_path(path: str) -> bool:
    """Skip known nondeterministic checkpoint fields."""
    if path in IGNORED_CHECKPOINT_PATHS:
        return True

    if path.startswith(IGNORED_CHECKPOINT_PATH_PREFIXES):
        return True

    path_leaf = path.rsplit(".", 1)[-1]
    if "[" in path_leaf:
        path_leaf = path_leaf.split("[", 1)[0]

    return path_leaf in IGNORED_CHECKPOINT_FIELD_NAMES


def should_skip_small_numeric(expected: float, actual: float) -> bool:
    """Skip comparisons when both values are effectively zero."""
    return abs(expected) < MIN_COMPARE_MAGNITUDE and abs(actual) < MIN_COMPARE_MAGNITUDE


def compare_checkpoint_values(expected, actual, path: str, summary: dict) -> None:
    """Recursively compare checkpoint values with type-aware rules."""
    if should_skip_checkpoint_path(path):
        return

    if isinstance(expected, dict) and isinstance(actual, dict):
        expected_keys = set(expected.keys())
        actual_keys = set(actual.keys())

        for missing_key in sorted(expected_keys - actual_keys):
            record_mismatch(
                summary,
                f"{path}.{missing_key}",
                "missing key in restored checkpoint",
                expected[missing_key],
                "<missing>",
            )

        for extra_key in sorted(actual_keys - expected_keys):
            record_mismatch(
                summary,
                f"{path}.{extra_key}",
                "unexpected key in restored checkpoint",
                "<missing>",
                actual[extra_key],
            )

        for shared_key in sorted(expected_keys & actual_keys):
            compare_checkpoint_values(expected[shared_key], actual[shared_key], f"{path}.{shared_key}", summary)
        return

    if isinstance(expected, list) and isinstance(actual, list):
        shared_len = min(len(expected), len(actual))

        for idx in range(shared_len):
            compare_checkpoint_values(expected[idx], actual[idx], f"{path}[{idx}]", summary)

        for idx in range(shared_len, len(expected)):
            record_mismatch(
                summary,
                f"{path}[{idx}]",
                "missing list element in restored checkpoint",
                expected[idx],
                "<missing>",
            )

        for idx in range(shared_len, len(actual)):
            record_mismatch(
                summary,
                f"{path}[{idx}]",
                "unexpected list element in restored checkpoint",
                "<missing>",
                actual[idx],
            )
        return

    if isinstance(expected, str) and isinstance(actual, str):
        expected_complex = parse_complex_string_magnitude(expected)
        actual_complex = parse_complex_string_magnitude(actual)

        if expected_complex and actual_complex:
            expected_mag, expected_suffix = expected_complex
            actual_mag, actual_suffix = actual_complex

            if should_skip_small_numeric(expected_mag, actual_mag):
                return

            if expected_suffix != actual_suffix:
                record_mismatch(
                    summary,
                    path,
                    "complex suffix mismatch",
                    expected,
                    actual,
                )
                return

            classification, _ = classify_percent_difference(expected_mag, actual_mag)
            if classification == "failed":
                record_mismatch(
                    summary,
                    path,
                    "complex magnitude differs by more than 10%",
                    expected,
                    actual,
                )
                return

            record_occurrence(summary, classification)
            return

        if expected == actual:
            record_occurrence(summary, "perfect")
        else:
            record_mismatch(summary, path, "string mismatch", expected, actual)
        return

    if is_numeric_value(expected) and is_numeric_value(actual):
        # Treat integer-to-integer values as exact matches; doubles use percent-based comparison.
        if isinstance(expected, int) and isinstance(actual, int):
            if expected == actual:
                record_occurrence(summary, "perfect")
            else:
                record_mismatch(summary, path, "integer mismatch", expected, actual)
            return

        if should_skip_small_numeric(float(expected), float(actual)):
            return

        classification, _ = classify_percent_difference(float(expected), float(actual))
        if classification == "failed":
            record_mismatch(summary, path, "double differs by more than 10%", expected, actual)
            return

        record_occurrence(summary, classification)
        return

    # All non-double and non-complex-string types require exact match.
    if expected == actual:
        record_occurrence(summary, "perfect")
    else:
        record_mismatch(summary, path, "type/value mismatch", expected, actual)


def compare_checkpoint_files(test_dir: Path, test_stem: str) -> dict:
    """Compare full checkpoint against restored checkpoint using type-aware rules."""
    full_checkpoint_path = test_dir / f"{test_stem}_full_checkpoint.json"

    restored_candidates = [
        test_dir / f"{test_stem}_restored_checkpoint.json",
        test_dir / "_checkpoint.json",
        test_dir / f"{test_stem}_checkpoint.json",
    ]

    restored_checkpoint_path = None
    for candidate in restored_candidates:
        if candidate.exists() and candidate.is_file():
            restored_checkpoint_path = candidate
            break

    if not full_checkpoint_path.exists() or not full_checkpoint_path.is_file():
        raise FileNotFoundError(f"Missing full checkpoint file: {full_checkpoint_path.name}")

    if restored_checkpoint_path is None:
        raise FileNotFoundError("No restored checkpoint file found")

    with full_checkpoint_path.open("r", encoding="utf-8") as f:
        full_data = json.load(f)

    with restored_checkpoint_path.open("r", encoding="utf-8") as f:
        restored_data = json.load(f)

    summary = {
        "perfect": 0,
        "acceptable": 0,
        "failed": 0,
        "numeric_failed": 0,
        "exact_failed": 0,
        "total": 0,
        "mismatch_samples": [],
        "full_checkpoint": str(full_checkpoint_path),
        "restored_checkpoint": str(restored_checkpoint_path),
    }

    compare_checkpoint_values(full_data, restored_data, "$", summary)
    return summary


def extract_rng_snapshot(full_checkpoint_path: Path) -> tuple[int | None, dict[str, int], dict[str, dict[int, int]]]:
    """Extract global randomseed and object rng_state values from a checkpoint."""
    with full_checkpoint_path.open("r", encoding="utf-8") as f:
        checkpoint_data = json.load(f)

    globals_obj = checkpoint_data.get("globals", {})
    randomseed = globals_obj.get("randomseed") if isinstance(globals_obj, dict) else None

    rng_by_object_name: dict[str, int] = {}
    rng_by_class_index: dict[str, dict[int, int]] = {}
    objects = checkpoint_data.get("objects", {})
    if isinstance(objects, dict):
        for class_name, class_payload in objects.items():
            if not isinstance(class_payload, dict):
                continue

            instances = class_payload.get("instances", [])
            if not isinstance(instances, list):
                continue

            class_rng_states: dict[int, int] = {}
            for idx, instance in enumerate(instances):
                if not isinstance(instance, dict):
                    continue

                name = instance.get("name")
                rng_state = instance.get("rng_state")
                if not isinstance(rng_state, int):
                    continue

                class_rng_states[idx] = rng_state
                if isinstance(name, str):
                    rng_by_object_name[name] = rng_state

            if class_rng_states and isinstance(class_name, str):
                rng_by_class_index[class_name] = class_rng_states

    return randomseed, rng_by_object_name, rng_by_class_index


def create_rng_pinned_test_file(test_dir: Path, test_file_name: str, test_stem: str, full_checkpoint_path: Path) -> tuple[Path | None, dict]:
    """Create a temporary test file pinned to RNG values captured from the Step 1 full run."""
    summary = {
        "randomseed_in_full": False,
        "randomseed_applied": False,
        "rng_states_extracted": 0,
        "rng_states_applied": 0,
        "named_rng_states": 0,
        "class_index_rng_states": 0,
        "pinned_file_created": False,
    }

    if not full_checkpoint_path.exists() or not full_checkpoint_path.is_file():
        return None, summary

    randomseed, rng_by_object_name, rng_by_class_index = extract_rng_snapshot(full_checkpoint_path)
    summary["randomseed_in_full"] = isinstance(randomseed, int)
    summary["named_rng_states"] = len(rng_by_object_name)
    summary["class_index_rng_states"] = sum(len(v) for v in rng_by_class_index.values())
    summary["rng_states_extracted"] = summary["class_index_rng_states"]

    test_file_path = test_dir / test_file_name
    if not test_file_path.exists() or not test_file_path.is_file():
        return None, summary

    with test_file_path.open("r", encoding="utf-8") as f:
        model_data = json.load(f)

    changed = False

    if isinstance(randomseed, int):
        directives = model_data.setdefault("_directives", {})
        if isinstance(directives, dict):
            set_directive = directives.setdefault("#set", {})
            if isinstance(set_directive, dict):
                if set_directive.get("randomseed") != randomseed:
                    set_directive["randomseed"] = randomseed
                    changed = True
                    summary["randomseed_applied"] = True

    objects = model_data.get("objects", {})
    if isinstance(objects, dict) and (rng_by_object_name or rng_by_class_index):
        for class_name, class_payload in objects.items():
            if not isinstance(class_payload, dict):
                continue

            instances = class_payload.get("instances", [])
            if not isinstance(instances, list):
                continue

            class_rng_states = rng_by_class_index.get(class_name, {}) if isinstance(class_name, str) else {}

            for idx, instance in enumerate(instances):
                if not isinstance(instance, dict):
                    continue

                target_rng_state = None
                name = instance.get("name")
                if isinstance(name, str) and name in rng_by_object_name:
                    target_rng_state = rng_by_object_name[name]
                elif idx in class_rng_states:
                    target_rng_state = class_rng_states[idx]

                if isinstance(target_rng_state, int) and instance.get("rng_state") != target_rng_state:
                    instance["rng_state"] = target_rng_state
                    changed = True
                    summary["rng_states_applied"] += 1

    if not changed:
        return None, summary

    backup_file_path = test_dir / f"{test_file_name}.rng_backup"
    shutil.copy2(test_file_path, backup_file_path)

    with test_file_path.open("w", encoding="utf-8") as f:
        json.dump(model_data, f, indent=2)
        f.write("\n")

    summary["pinned_file_created"] = True
    return backup_file_path, summary


def prepare_seed_pinned_test_file(test_dir: Path, test_file_name: str, test_stem: str) -> tuple[Path | None, dict]:
    """Ensure a deterministic randomseed is present before running Step 1/2/3."""
    summary = {
        "seed_present": False,
        "seed_value": None,
        "seed_source": "none",
        "file_patched": False,
    }

    test_file_path = test_dir / test_file_name
    if not test_file_path.exists() or not test_file_path.is_file():
        return None, summary

    with test_file_path.open("r", encoding="utf-8") as f:
        model_data = json.load(f)

    directives = model_data.setdefault("_directives", {})
    if not isinstance(directives, dict):
        return None, summary

    set_directive = directives.setdefault("#set", {})
    if not isinstance(set_directive, dict):
        return None, summary

    def parse_existing_seed(raw_seed):
        if isinstance(raw_seed, bool):
            return None
        if isinstance(raw_seed, int):
            return raw_seed
        if isinstance(raw_seed, float):
            return int(raw_seed)
        if isinstance(raw_seed, str):
            cleaned = raw_seed.strip()
            if cleaned.endswith(";"):
                cleaned = cleaned[:-1].strip()
            if cleaned == "":
                return None
            try:
                return int(cleaned, 10)
            except ValueError:
                try:
                    return int(float(cleaned))
                except ValueError:
                    return None
        return None

    changed = False
    existing_seed = parse_existing_seed(set_directive.get("randomseed"))
    if existing_seed is not None:
        summary["seed_present"] = True
        summary["seed_value"] = existing_seed
        summary["seed_source"] = "existing"
    else:
        seed_value = int(zlib.crc32(test_stem.encode("utf-8")) & 0x7FFFFFFF)
        if seed_value == 0:
            seed_value = 1
        set_directive["randomseed"] = seed_value
        summary["seed_present"] = True
        summary["seed_value"] = seed_value
        summary["seed_source"] = "generated"
        changed = True

    if not changed:
        return None, summary

    backup_file_path = test_dir / f"{test_file_name}.seed_backup"
    shutil.copy2(test_file_path, backup_file_path)

    with test_file_path.open("w", encoding="utf-8") as f:
        json.dump(model_data, f, indent=2)
        f.write("\n")

    summary["file_patched"] = True
    return backup_file_path, summary

def parse_difference_count(output: str, returncode: int):
    """
    Parse test_gldapi compare output to extract difference count.
    
    Returns: int (number of differences) or None if unable to parse
    """
    # Legacy helper retained for compatibility with previous compare output parsing.
    # If return code is 0, there are 0 differences
    if returncode == 0:
        return 0
    
    # Look for patterns in output that indicate difference count
    
    # Try to find patterns like "X differences" or "X errors" or "X mismatches"
    patterns = [
        r'(\d+)\s+differences?',
        r'(\d+)\s+error',
        r'(\d+)\s+mismatch',
        r'(\d+)\s+value.*differ',
    ]
    
    for pattern in patterns:
        match = re.search(pattern, output, re.IGNORECASE)
        if match:
            return int(match.group(1))
    
    # If error occurred but we can't parse difference count, indicate failure
    if returncode != 0:
        return None
    
    return 0

def getTestGldApiBinary():
    """
    Check development environment for the test_gldapi binary file.
    """
    global testGldApiBinary
    testGldApiBinary = shutil.which("test_gldapi")
    if not testGldApiBinary:
        rootPath = Path(__file__).parent.resolve()
        for child in rootPath.iterdir():
            if child.is_dir():
                childBin = child / "bin" / "test_gldapi"
                childBin.resolve()
                if childBin.exists() and childBin.is_file():
                    testGldApiBinary = str(childBin)
                    break
    if not testGldApiBinary:
        raise ModuleNotFoundError("Could not find the test_gldapi binary in the development environment!")


def contains_deltamode_json(value) -> bool:
    """Recursively detect DELTAMODE activation markers in converted JSON tests."""
    if isinstance(value, dict):
        for key, child in value.items():
            lowered_key = str(key).lower()
            if lowered_key in {
                "deltamode_timestep",
                "deltamode_maximumtime",
                "deltamode_iteration_limit",
                "deltamode_forced_extra_timesteps",
                "deltamode_forced_always",
            }:
                return True
            if lowered_key == "enable_subsecond_models" and child is True:
                return True
            if contains_deltamode_json(child):
                return True
        return False

    if isinstance(value, list):
        return any(contains_deltamode_json(child) for child in value)

    if isinstance(value, str):
        return value.strip().upper() == "DELTAMODE"

    return False


def is_deltamode_test(test_file: Path) -> tuple[bool, str]:
    """Detect whether a test enables DELTAMODE and should be skipped."""
    try:
        if test_file.suffix == ".json":
            with test_file.open("r", encoding="utf-8") as f:
                data = json.load(f)
            if contains_deltamode_json(data):
                return True, "DELTAMODE activated"
            return False, ""

        text = test_file.read_text(encoding="utf-8", errors="ignore")
    except Exception as exc:
        return False, f"detection error ignored: {exc}"

    for raw_line in text.splitlines():
        line = raw_line.split("//", 1)[0].strip()
        if not line:
            continue

        upper_line = line.upper()
        lower_line = line.lower()

        if "FLAGS DELTAMODE" in upper_line:
            return True, "DELTAMODE activated"
        if "ENABLE_SUBSECOND_MODELS TRUE" in upper_line:
            return True, "DELTAMODE activated"
        if lower_line.startswith("#set ") and "deltamode_" in lower_line:
            return True, "DELTAMODE activated"
        if "deltamode_timestep" in lower_line:
            return True, "DELTAMODE activated"

    return False, ""

def is_error_test(test_file: Path) -> tuple[bool, str]:
    """Detect whether a test is an error test (_err_) and should be skipped."""
    
    if "_err" in test_file.stem:
        return True, "ERROR test"
    else:
        return False, ""

def is_excluded_test(test_file: Path) -> tuple[bool, str]:
    """Detect whether a test is part of excludeTests and should be skipped."""
    
    global excludeTests
    
    if test_file.stem in excludeTests:
        return True, "Excluded test"
    else:
        return False, ""

def processModuleDirectory(moduleDirectory: Path, runOptionalTests: bool):
    """
    Search through a module directory for a directory called autotest.
    Capture all autotest files present in the autotest directory.
    """
    global autotestFiles
    noValidateFile = moduleDirectory / "validate.no"
    noValidateFile.resolve()
    if not noValidateFile.exists():    
        autotestDirectory = moduleDirectory / "autotest"
        autotestDirectory.resolve()
        if autotestDirectory.exists() and autotestDirectory.is_dir():
            for autotestChild in autotestDirectory.iterdir():
                autotestChild.resolve()
                if (autotestChild.is_file() 
                        and autotestChild.suffix == ".json"
                        and "test_" in autotestChild.stem
                        and (("_opt" in autotestChild.stem and runOptionalTests) or "_opt" not in autotestChild.stem)):
                    autotestFiles.append(autotestChild)
                    # Create working directory
                    autotestDir = autotestChild.parent / autotestChild.stem
                    autotestDir.resolve()
                    if not autotestDir.exists():
                        autotestDir.mkdir()
                    # Copy test file to working directory
                    shutil.copy(autotestChild, autotestDir)

def runCheckpointTest(testFile: Path, keepCheckpoints: bool = False, verbose: bool = False) -> TestResult:
    """
    Run a single test through the 4-step checkpoint process.
    
    Returns: TestResult object
    """
    result = TestResult(testFile)

    should_skip, skip_reason = is_deltamode_test(testFile)
    if should_skip:
        result.skipped = True
        result.skip_reason = skip_reason
        print(f"[{testFile.name}] SKIPPED: {skip_reason}", flush=True)
        return result
    
    #Do the same for _err files
    should_skip, skip_reason = is_error_test(testFile)
    if should_skip:
        result.skipped = True
        result.skip_reason = skip_reason
        print(f"[{testFile.name}] SKIPPED: {skip_reason}", flush=True)
        return result
    
    #Do the same for explicitly excluded files
    should_skip, skip_reason = is_excluded_test(testFile)
    if should_skip:
        result.skipped = True
        result.skip_reason = skip_reason
        print(f"[{testFile.name}] SKIPPED: {skip_reason}", flush=True)
        return result
	
    # Ensure binary is found (needed for multiprocessing spawn mode)
    global testGldApiBinary
    if not testGldApiBinary:
        getTestGldApiBinary()
    
    if not testGldApiBinary:
        result.step_failed = 1
        result.error_message = "test_gldapi binary not found"
        return result
    
    # Get the test working directory
    testDir = testFile.parent / testFile.stem
    testDir.resolve()
    testFileName = testFile.name
    run_env = build_gld_environment()
    # Preserve generated artifacts for debugging/verification.
    # Intentionally skip cleanup before running steps.
    seed_backup_file: Path | None = None
    seed_pin_summary: dict = {}
    checkpoint_test_file_name = testFileName
    
    try:
        seed_backup_file, seed_pin_summary = prepare_seed_pinned_test_file(testDir, testFileName, testFile.stem)

        # Step 1: Baseline run
        print(f"[{testFile.name}] Step 1/4: Baseline run...", end=" ", flush=True)
        step1_command = [testGldApiBinary, testFileName]
        step1_result = run_process(step1_command, testDir, run_env, 300, verbose)
        
        if step1_result.returncode != 0:
            if not verbose:
                step1_result = run_process(step1_command, testDir, run_env, 300, True)
            result.step_failed = 1
            result.error_message = "Baseline run failed"
            result.details['step_1'] = (step1_result.stdout or "") + (step1_result.stderr or "")
            print("FAILED")
            return result
        print("OK")

        # Step 2: Partial run with checkpoint (1 timestep)
        print(f"[{testFile.name}] Step 2/4: Checkpoint at 1 timestep...", end=" ", flush=True)
        step2_command = [testGldApiBinary, checkpoint_test_file_name, "--checkpoint", "--steps", "1"]
        step2_result = run_process(step2_command, testDir, run_env, 300, verbose)
        
        if step2_result.returncode != 0:
            if not verbose:
                step2_result = run_process(step2_command, testDir, run_env, 300, True)
            result.step_failed = 2
            result.error_message = "Checkpoint creation failed"
            result.details['step_2'] = (step2_result.stdout or "") + (step2_result.stderr or "")
            print("FAILED")
            return result
        print("OK")
        
        # Step 3: Restore from checkpoint
        print(f"[{testFile.name}] Step 3/4: Restore from checkpoint...", end=" ", flush=True)
        step3_command = [testGldApiBinary, checkpoint_test_file_name, "--restore"]
        step3_result = run_process(step3_command, testDir, run_env, 300, verbose)
        
        if step3_result.returncode != 0:
            if not verbose:
                step3_result = run_process(step3_command, testDir, run_env, 300, True)
            result.step_failed = 3
            result.error_message = "Checkpoint restore failed"
            result.details['step_3'] = (step3_result.stdout or "") + (step3_result.stderr or "")
            print("FAILED")
            return result
        print("OK")
        
        # Step 4: Compare results with type-aware percentage checks
        print(f"[{testFile.name}] Step 4/4: Compare results...", end=" ", flush=True)
        try:
            compare_summary = compare_checkpoint_files(testDir, testFile.stem)
        except Exception as compare_error:
            result.step_failed = 4
            result.error_message = f"Comparison failed: {compare_error}"
            print("FAILED")
            return result

        result.perfect_occurrences = compare_summary["perfect"]
        result.acceptable_occurrences = compare_summary["acceptable"]
        result.failed_occurrences = compare_summary["failed"]
        result.numeric_failed_occurrences = compare_summary["numeric_failed"]
        result.exact_failed_occurrences = compare_summary["exact_failed"]
        result.total_occurrences = compare_summary["total"]
        result.differences = result.failed_occurrences
        result.details["step_4"] = {
            "full_checkpoint": compare_summary["full_checkpoint"],
            "restored_checkpoint": compare_summary["restored_checkpoint"],
            "numeric_failed": compare_summary["numeric_failed"],
            "exact_failed": compare_summary["exact_failed"],
            "mismatch_samples": compare_summary["mismatch_samples"],
        }

        print("OK")
        if result.failed_occurrences > 0:
            print(
                f"[{testFile.name}] FAILED: {result.failed_occurrences}/{result.total_occurrences} parameter checks failed "
                f"(numeric>10%={result.numeric_failed_occurrences}, exact={result.exact_failed_occurrences})"
            )
        elif result.acceptable_occurrences > 0:
            print(
                f"[{testFile.name}] ACCEPTABLE: {result.acceptable_occurrences}/{result.total_occurrences} within 5-10%"
            )
        else:
            print(f"[{testFile.name}] PERFECT: {result.perfect_occurrences}/{result.total_occurrences} within 5%")

        # Preserve generated artifacts for debugging/verification.
        # Intentionally skip cleanup after running steps.
        return result
        
    except subprocess.TimeoutExpired:
        result.step_failed = result.step_failed if result.step_failed else 1
        result.error_message = "Timeout exceeded (300s)"
        print(f"TIMEOUT")
        return result
    except Exception as e:
        result.step_failed = result.step_failed if result.step_failed else 1
        result.error_message = f"Exception: {str(e)}"
        print(f"ERROR: {str(e)}")
        return result
    finally:
        if seed_backup_file is not None and seed_backup_file.exists() and seed_backup_file.is_file():
            test_file_path = testDir / testFileName
            shutil.move(str(seed_backup_file), str(test_file_path))

def getGLDVersionInfo() -> str:
    """
    Get the GridLAB-D version information.
    """
    try:
        command = [testGldApiBinary, "--version"]
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except:
        pass
    return "Unknown GridLAB-D version"

def processResults(results: list, resultsFile: Path, testPerformance: int, keepCheckpoints: bool) -> int:
    """
    Process the results and output to checkpoint_results.txt
    """
    global autotestFiles
    rv = 0
    gldInfo = getGLDVersionInfo()
    
    # Categorize results
    skipped_tests = []         # DELTAMODE-enabled or ERRor tests not run
    perfect_tests = []         # All compared values are within 5% or exact by type
    acceptable_tests = []      # No failures, at least one 5-10% occurrence
    failed_compare_tests = []  # Completed but has >10% or exact-match failures
    incomplete_tests = []      # Didn't complete checkpoint process
    skipped_tests = []      # DELTAMODE-enabled/ERRor tests/explicit skips not run
    perfect_tests = []      # 0 differences
    acceptable_tests = []   # > 0 differences but completed
    failed_tests = []       # Didn't complete checkpoint process
    
    for result in results:
        if result.skipped:
            skipped_tests.append(result)
        elif result.step_failed:
            incomplete_tests.append(result)
        elif result.failed_occurrences > 0:
            failed_compare_tests.append(result)
        elif result.acceptable_occurrences > 0:
            acceptable_tests.append(result)
        elif result.total_occurrences > 0:
            perfect_tests.append(result)
        else:
            incomplete_tests.append(result)
    
    # Sort by occurrence counts for easier triage.
    acceptable_tests.sort(key=lambda r: r.acceptable_occurrences, reverse=True)
    failed_compare_tests.sort(key=lambda r: r.failed_occurrences, reverse=True)
    
    with resultsFile.open("w") as f:
        f.write(f"GridLAB-D Checkpoint Validation Results\n")
        f.write(f"{'='*60}\n\n")
        f.write(f"GridLAB-D Version Info:\n\t{gldInfo}\n\n")
        f.write("Checkpoint Test Results by Category:\n\n")
        
        # Perfect tests (0 differences)
        if skipped_tests:
            f.write(f"- Skipped (DELTAMODE/ERR/Exclude) - {len(skipped_tests)} tests:\n")
            for result in skipped_tests:
                f.write(f"\t{result}\n")
            f.write("\n")

        if perfect_tests:
            f.write(f"✓ Perfect Match (all numeric within 5%) - {len(perfect_tests)} tests:\n")
            for result in perfect_tests:
                f.write(f"\t{result}\n")
            f.write("\n")
        
        # Acceptable tests (no failures, some values in 5-10%)
        if acceptable_tests:
            f.write(f"≈ Acceptable Match (numeric within 10%) - {len(acceptable_tests)} tests:\n")
            for result in acceptable_tests:
                f.write(
                    f"\t{result.test_file.name} - acceptable={result.acceptable_occurrences}, total={result.total_occurrences}\n"
                )
            f.write("\n")

        # Failed comparisons
        if failed_compare_tests:
            f.write(f"✗ Failed Comparison (>10% or exact mismatch) - {len(failed_compare_tests)} tests:\n")
            for result in failed_compare_tests:
                f.write(
                    f"\t{result.test_file.name} - failed={result.failed_occurrences}, "
                    f"numeric_failed={result.numeric_failed_occurrences}, exact_failed={result.exact_failed_occurrences}, "
                    f"acceptable={result.acceptable_occurrences}, total={result.total_occurrences}\n"
                )
            f.write("\n")
        
        # Incomplete tests
        if incomplete_tests:
            f.write(f"✗ Incomplete (checkpoint process failed) - {len(incomplete_tests)} tests:\n")
            for result in incomplete_tests:
                f.write(f"\t{result}\n")
            f.write("\n")
        
        f.write(f"\n{'='*60}\n")
        f.write("Results Summary:\n")
        total_tests_discovered = len(results)
        total_tests_run = total_tests_discovered - len(skipped_tests)
        total_completed = len(perfect_tests) + len(acceptable_tests) + len(failed_compare_tests)
        f.write(f"\tTotal Tests Discovered: {total_tests_discovered}\n")
        f.write(f"\tTotal Tests Run: {total_tests_run}\n")
        f.write(f"\tSkipped (DELTAMODE/ERR): {len(skipped_tests)}\n")
        f.write(f"\tPerfect (<=5%): {len(perfect_tests)}\n")
        f.write(f"\tAcceptable (>5% and <=10%): {len(acceptable_tests)}\n")
        f.write(f"\tFailed Comparisons (>10% or exact mismatch): {len(failed_compare_tests)}\n")
        f.write(f"\tIncomplete: {len(incomplete_tests)}\n")

        f.write(f"\tSkipped (DELTAMODE/ERR/Exclude): {len(skipped_tests)}\n")
        f.write(f"\tPerfect (0 diff): {len(perfect_tests)}\n")
        f.write(f"\tAcceptable (>0 diff): {len(acceptable_tests)}\n")
        f.write(f"\tFailed (incomplete): {len(failed_tests)}\n")
        
        total_completed = len(perfect_tests) + len(acceptable_tests)
        if total_tests_run > 0:
            f.write(f"\tCompleted Rate: {math.floor((float(total_completed) / float(total_tests_run)) * 100.0)}%\n")

        completed_results = perfect_tests + acceptable_tests + failed_compare_tests
        if completed_results:
            total_perfect_occurrences = sum(r.perfect_occurrences for r in completed_results)
            total_acceptable_occurrences = sum(r.acceptable_occurrences for r in completed_results)
            total_failed_occurrences = sum(r.failed_occurrences for r in completed_results)
            total_numeric_failed_occurrences = sum(r.numeric_failed_occurrences for r in completed_results)
            total_exact_failed_occurrences = sum(r.exact_failed_occurrences for r in completed_results)
            total_occurrences = sum(r.total_occurrences for r in completed_results)
            f.write(f"\tCompared Parameters: {total_occurrences}\n")
            f.write(f"\tPerfect Occurrences (<=5%): {total_perfect_occurrences}\n")
            f.write(f"\tAcceptable Occurrences (>5% and <=10%): {total_acceptable_occurrences}\n")
            f.write(f"\tFailed Occurrences (>10% or exact mismatch): {total_failed_occurrences}\n")
            f.write(f"\tNumeric Failure Occurrences (>10%): {total_numeric_failed_occurrences}\n")
            f.write(f"\tExact Mismatch Occurrences: {total_exact_failed_occurrences}\n")

        f.write(f"\tTotal Test Time: {testPerformance} seconds\n")
        
        # Details on incomplete tests
        if incomplete_tests:
            f.write(f"\n{'='*60}\n")
            f.write("Incomplete Tests Details:\n\n")
            for result in incomplete_tests:
                f.write(f"{result.test_file.stem}:\n")
                if result.step_failed:
                    f.write(f"  Failed at Step: {result.step_failed}\n")
                if result.error_message:
                    f.write(f"  Error: {result.error_message}\n")
                f.write("\n")

        # Details on failed comparisons
        if failed_compare_tests:
            f.write(f"\n{'='*60}\n")
            f.write("Failed Comparison Details:\n\n")
            for result in failed_compare_tests:
                f.write(
                    f"{result.test_file.stem}: failed={result.failed_occurrences}, "
                    f"numeric_failed={result.numeric_failed_occurrences}, exact_failed={result.exact_failed_occurrences}, "
                    f"acceptable={result.acceptable_occurrences}, total={result.total_occurrences}\n"
                )
                mismatch_samples = result.details.get("step_4", {}).get("mismatch_samples", [])
                if mismatch_samples:
                    for sample in mismatch_samples:
                        f.write(
                            f"  - {sample['path']}: {sample['reason']}\n"
                        )
                f.write("\n")
    
    # Print summary to console
    print("\n" + "="*60)
    print("Checkpoint Testing Summary:")
    total_tests_discovered = len(results)
    total_tests_run = total_tests_discovered - len(skipped_tests)
    total_completed = len(perfect_tests) + len(acceptable_tests) + len(failed_compare_tests)
    print(f"  Total Tests Discovered: {total_tests_discovered}")
    print(f"  Total Tests Run: {total_tests_run}")
    print(f"  - Skipped (DELTAMODE/ERR): {len(skipped_tests)}")
    print(f"  ✓ Perfect (<=5%): {len(perfect_tests)}")
    print(f"  ≈ Acceptable (>5% and <=10%): {len(acceptable_tests)}")
    print(f"  ✗ Failed Comparisons (>10% or exact mismatch): {len(failed_compare_tests)}")
    print(f"  ✗ Incomplete: {len(incomplete_tests)}")
    print(f"  - Skipped (DELTAMODE/ERR/Exclude): {len(skipped_tests)}")
    print(f"  ✓ Perfect (0 differences): {len(perfect_tests)}")
    print(f"  ≈ Acceptable (with differences): {len(acceptable_tests)}")
    print(f"  ✗ Failed (incomplete): {len(failed_tests)}")
    total_completed = len(perfect_tests) + len(acceptable_tests)
    if total_tests_run > 0:
        print(f"  Completed Rate: {math.floor((float(total_completed) / float(total_tests_run)) * 100.0)}%")

    completed_results = perfect_tests + acceptable_tests + failed_compare_tests
    if completed_results:
        total_perfect_occurrences = sum(r.perfect_occurrences for r in completed_results)
        total_acceptable_occurrences = sum(r.acceptable_occurrences for r in completed_results)
        total_failed_occurrences = sum(r.failed_occurrences for r in completed_results)
        total_numeric_failed_occurrences = sum(r.numeric_failed_occurrences for r in completed_results)
        total_exact_failed_occurrences = sum(r.exact_failed_occurrences for r in completed_results)
        total_occurrences = sum(r.total_occurrences for r in completed_results)
        print(f"  Compared Parameters: {total_occurrences}")
        print(f"  Perfect Occurrences (<=5%): {total_perfect_occurrences}")
        print(f"  Acceptable Occurrences (>5% and <=10%): {total_acceptable_occurrences}")
        print(f"  Failed Occurrences (>10% or exact mismatch): {total_failed_occurrences}")
        print(f"  Numeric Failure Occurrences (>10%): {total_numeric_failed_occurrences}")
        print(f"  Exact Mismatch Occurrences: {total_exact_failed_occurrences}")

    print(f"  Total Test Time: {testPerformance} seconds")
    print(f"  Results written to: {resultsFile}")
    print("="*60 + "\n")
    
    # Return non-zero if any tests are incomplete or have failed comparisons.
    if incomplete_tests or failed_compare_tests:
        rv = 1
    
    return rv

def main(module: str, runOptionalTests: bool, threads: int, keepCheckpoints: bool, verbose: bool):
    global autotestFiles
    rv = 0
    
    multiprocessing.set_start_method("spawn", force=True)
    procs = 1
    if threads < 1:
        procs = multiprocessing.cpu_count()
    else:
        procs = min(threads, multiprocessing.cpu_count())
    
    getTestGldApiBinary()
    
    searchDirectoryBase = Path(__file__).parent.resolve()
    moduleDirectory = None
    resultsFile = searchDirectoryBase / "checkpoint_results.txt"
    resultsFile.resolve()
    
    if resultsFile.exists():
        resultsFile.unlink()
    
    print(f"GridLAB-D Checkpoint Validation")
    print(f"{'='*60}")
    print(f"Using test_gldapi binary: {testGldApiBinary}")
    print(f"Parallel threads: {procs}")
    if module != "all":
        print(f"Module: {module}")
    print(f"{'='*60}\n")
    
    # Search for autotest files
    if module != "all":
        moduleDirectory = searchDirectoryBase / module
        moduleDirectory.resolve()
        if not moduleDirectory.exists() or not moduleDirectory.is_dir():
            raise IOError(f"The module, {module}, does not exist.")
        processModuleDirectory(moduleDirectory, runOptionalTests)
    else:
        for moduleChild in searchDirectoryBase.iterdir():
            if moduleChild.is_dir() and not moduleChild.name.startswith('.'):
                # Skip common non-module directories
                skip_dirs = ['build', 'bin', '.venv', 'node_modules', '_test_results']
                if moduleChild.name not in skip_dirs:
                    processModuleDirectory(moduleChild.resolve(), runOptionalTests)
    
    # Run checkpoint tests in parallel
    autotestFiles.sort(key=lambda x: str(x))
    
    if len(autotestFiles) > 0:
        procs = min(procs, len(autotestFiles))
        print(f"Discovered {len(autotestFiles)} test files\n")
        print(f"{'='*60}")
        print("Starting checkpoint tests...\n")
        
        results = []
        startTime = time.perf_counter()
        
        run_args = [(test_file, keepCheckpoints, verbose) for test_file in autotestFiles]
        with multiprocessing.Pool(procs) as p:
            results = p.starmap(runCheckpointTest, run_args)
        
        endTime = time.perf_counter()
        testPerformance = math.ceil(endTime - startTime)
        
        print(f"\n{'='*60}")
        rv = processResults(results, resultsFile, testPerformance, keepCheckpoints)
        
    elif module != "all":
        print(f"No autotest files were found recursively searching from {moduleDirectory}. Exiting.")
    else:
        print(f"No autotest files were found recursively searching from {searchDirectoryBase}. Exiting.")
    
    if rv == 1:
        sys.exit(1)

if __name__ == "__main__":
    parser = ArgumentParser(description="Validate GridLAB-D checkpoint functionality by running autotests through a 4-step checkpoint process.")
    parser.add_argument(
        "-m",
        "--module",
        type=str,
        default="all",
        help="The specific module to validate. Default is all modules."
    )
    parser.add_argument(
        "-t",
        "--threads",
        type=int,
        default=0,
        help="Number of parallel threads (0 = CPU count, default)."
    )
    parser.add_argument(
        "-o",
        "--run_optional_tests",
        action="store_true",
        help="Run optional tests (those with _opt suffix) as well."
    )
    parser.add_argument(
        "--keep-checkpoints",
        action="store_true",
        help="Keep checkpoint files after testing (default: delete)."
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print detailed output for each test."
    )
    
    args = parser.parse_args()
    
    try:
        main(
            module=args.module,
            runOptionalTests=args.run_optional_tests,
            threads=args.threads,
            keepCheckpoints=args.keep_checkpoints,
            verbose=args.verbose
        )
    except ModuleNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except IOError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nValidation interrupted by user.", file=sys.stderr)
        sys.exit(130)
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        sys.exit(1)
