#!/usr/bin/env python3
"""
GridLAB-D Checkpoint Validation Script

Runs all autotests through a 4-step checkpoint process:
1. Baseline run
2. Partial run with checkpoint (1 timestep)
3. Restore from checkpoint
4. Compare results

Usage:
    python3 validate_checkpoint.py [-m MODULE] [-t THREADS] [-o] [--keep-checkpoints] [--verbose]
"""

from argparse import ArgumentParser
from pathlib import Path
import math
import multiprocessing
import shutil
import subprocess
import sys
import time
import os
import json

# Global state
autotestFiles = []
gldBinary = None
testGldApiBinary = None
#Autotests to explicitly exclude from checkpointing
excludeTests = ["test_cloud_tmy2_converted", "test_cloud_tmy3_converted"]

def cleanup_test_artifacts(test_dir: Path, test_stem: str) -> None:
    """Remove checkpoint files generated by test_gldapi from a test working directory."""
    artifact_names = {
        f"{test_stem}_full_checkpoint.json",
        f"{test_stem}_partial_checkpoint.json",
        f"{test_stem}_restored_checkpoint.json",
        f"{test_stem}_checkpoint.json",
        "_checkpoint.json",
    }

    for artifact_name in artifact_names:
        artifact_path = test_dir / artifact_name
        if artifact_path.exists() and artifact_path.is_file():
            artifact_path.unlink()


def run_process(command: list[str], cwd: Path, env: dict, timeout: int, capture_output: bool):
    """Run a subprocess with fast success-path defaults and optional output capture."""
    if capture_output:
        return subprocess.run(
            command,
            cwd=cwd,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    return subprocess.run(
        command,
        cwd=cwd,
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        timeout=timeout,
        text=True,
    )


def build_gld_environment() -> dict:
    """Build the GridLAB-D runtime environment used by the launch profiles."""
    env = os.environ.copy()

    if testGldApiBinary:
        build_dir = str(Path(testGldApiBinary).resolve().parent.parent)
    else:
        build_dir = str((Path(__file__).parent / "build").resolve())

    build_bin = os.path.join(build_dir, "bin")
    build_lib = os.path.join(build_dir, "lib")
    build_share = os.path.join(build_dir, "share")
    path_sep = os.pathsep

    env["PATH"] = build_bin + path_sep + env.get("PATH", "")
    env["LD_LIBRARY_PATH"] = build_lib + path_sep + env.get("LD_LIBRARY_PATH", "")
    env["GLPATH"] = path_sep.join([build_lib, build_share, build_dir])
    env["GRIDLABD_HOME"] = build_dir
    return env

class TestResult:
    """Encapsulates the result of a checkpoint test"""
    
    def __init__(self, test_file: Path):
        self.test_file = test_file
        self.skipped = False
        self.skip_reason = ""
        self.step_failed = None  # Which step failed (1-4)
        self.error_message = ""
        self.differences = None  # Number of differences found (None if didn't reach Step 4)
        self.details = {}
        
    def __repr__(self):
        if self.skipped:
            if self.skip_reason:
                return f"[SKIPPED] {self.test_file.name} - {self.skip_reason}"
            return f"[SKIPPED] {self.test_file.name}"
        if self.step_failed:
            msg = f"[INCOMPLETE] {self.test_file.name}"
            if self.step_failed:
                msg += f" - Failed at Step {self.step_failed}"
            if self.error_message:
                msg += f": {self.error_message}"
            return msg
        elif self.differences is not None:
            if self.differences == 0:
                return f"[0 differences] {self.test_file.name}"
            else:
                return f"[{self.differences} differences] {self.test_file.name}"
        else:
            return f"[ERROR] {self.test_file.name} - No comparison data"

def parse_difference_count(output: str, returncode: int):
    """
    Parse test_gldapi compare output to extract difference count.
    
    Returns: int (number of differences) or None if unable to parse
    """
    # If return code is 0, there are 0 differences
    if returncode == 0:
        return 0
    
    # Look for patterns in output that indicate difference count
    import re
    
    # Try to find patterns like "X differences" or "X errors" or "X mismatches"
    patterns = [
        r'(\d+)\s+differences?',
        r'(\d+)\s+error',
        r'(\d+)\s+mismatch',
        r'(\d+)\s+value.*differ',
    ]
    
    for pattern in patterns:
        match = re.search(pattern, output, re.IGNORECASE)
        if match:
            return int(match.group(1))
    
    # If error occurred but we can't parse difference count, indicate failure
    if returncode != 0:
        return None
    
    return 0

def getTestGldApiBinary():
    """
    Check development environment for the test_gldapi binary file.
    """
    global testGldApiBinary
    testGldApiBinary = shutil.which("test_gldapi")
    if not testGldApiBinary:
        rootPath = Path(__file__).parent.resolve()
        for child in rootPath.iterdir():
            if child.is_dir():
                childBin = child / "bin" / "test_gldapi"
                childBin.resolve()
                if childBin.exists() and childBin.is_file():
                    testGldApiBinary = str(childBin)
                    break
    if not testGldApiBinary:
        raise ModuleNotFoundError("Could not find the test_gldapi binary in the development environment!")


def contains_deltamode_json(value) -> bool:
    """Recursively detect DELTAMODE activation markers in converted JSON tests."""
    if isinstance(value, dict):
        for key, child in value.items():
            lowered_key = str(key).lower()
            if lowered_key in {
                "deltamode_timestep",
                "deltamode_maximumtime",
                "deltamode_iteration_limit",
                "deltamode_forced_extra_timesteps",
                "deltamode_forced_always",
            }:
                return True
            if lowered_key == "enable_subsecond_models" and child is True:
                return True
            if contains_deltamode_json(child):
                return True
        return False

    if isinstance(value, list):
        return any(contains_deltamode_json(child) for child in value)

    if isinstance(value, str):
        return value.strip().upper() == "DELTAMODE"

    return False


def is_deltamode_test(test_file: Path) -> tuple[bool, str]:
    """Detect whether a test enables DELTAMODE and should be skipped."""
    try:
        if test_file.suffix == ".json":
            with test_file.open("r", encoding="utf-8") as f:
                data = json.load(f)
            if contains_deltamode_json(data):
                return True, "DELTAMODE activated"
            return False, ""

        text = test_file.read_text(encoding="utf-8", errors="ignore")
    except Exception as exc:
        return False, f"detection error ignored: {exc}"

    for raw_line in text.splitlines():
        line = raw_line.split("//", 1)[0].strip()
        if not line:
            continue

        upper_line = line.upper()
        lower_line = line.lower()

        if "FLAGS DELTAMODE" in upper_line:
            return True, "DELTAMODE activated"
        if "ENABLE_SUBSECOND_MODELS TRUE" in upper_line:
            return True, "DELTAMODE activated"
        if lower_line.startswith("#set ") and "deltamode_" in lower_line:
            return True, "DELTAMODE activated"
        if "deltamode_timestep" in lower_line:
            return True, "DELTAMODE activated"

    return False, ""

def is_error_test(test_file: Path) -> tuple[bool, str]:
    """Detect whether a test is an error test (_err_) and should be skipped."""
    
    if "_err" in test_file.stem:
        return True, "ERROR test"
    else:
        return False, ""

def is_excluded_test(test_file: Path) -> tuple[bool, str]:
    """Detect whether a test is part of excludeTests and should be skipped."""
    
    global excludeTests
    
    if test_file.stem in excludeTests:
        return True, "Excluded test"
    else:
        return False, ""

def processModuleDirectory(moduleDirectory: Path, runOptionalTests: bool):
    """
    Search through a module directory for a directory called autotest.
    Capture all autotest files present in the autotest directory.
    """
    global autotestFiles
    noValidateFile = moduleDirectory / "validate.no"
    noValidateFile.resolve()
    if not noValidateFile.exists():    
        autotestDirectory = moduleDirectory / "autotest"
        autotestDirectory.resolve()
        if autotestDirectory.exists() and autotestDirectory.is_dir():
            for autotestChild in autotestDirectory.iterdir():
                autotestChild.resolve()
                if (autotestChild.is_file() 
                        and autotestChild.suffix == ".json"
                        and "test_" in autotestChild.stem
                        and (("_opt" in autotestChild.stem and runOptionalTests) or "_opt" not in autotestChild.stem)):
                    autotestFiles.append(autotestChild)
                    # Create working directory
                    autotestDir = autotestChild.parent / autotestChild.stem
                    autotestDir.resolve()
                    if not autotestDir.exists():
                        autotestDir.mkdir()
                    # Copy test file to working directory
                    shutil.copy(autotestChild, autotestDir)

def runCheckpointTest(testFile: Path, keepCheckpoints: bool = False, verbose: bool = False) -> TestResult:
    """
    Run a single test through the 4-step checkpoint process.
    
    Returns: TestResult object
    """
    result = TestResult(testFile)

    should_skip, skip_reason = is_deltamode_test(testFile)
    if should_skip:
        result.skipped = True
        result.skip_reason = skip_reason
        print(f"[{testFile.name}] SKIPPED: {skip_reason}", flush=True)
        return result
    
    #Do the same for _err files
    should_skip, skip_reason = is_error_test(testFile)
    if should_skip:
        result.skipped = True
        result.skip_reason = skip_reason
        print(f"[{testFile.name}] SKIPPED: {skip_reason}", flush=True)
        return result
    
    #Do the same for explicitly excluded files
    should_skip, skip_reason = is_excluded_test(testFile)
    if should_skip:
        result.skipped = True
        result.skip_reason = skip_reason
        print(f"[{testFile.name}] SKIPPED: {skip_reason}", flush=True)
        return result
	
    # Ensure binary is found (needed for multiprocessing spawn mode)
    global testGldApiBinary
    if not testGldApiBinary:
        getTestGldApiBinary()
    
    if not testGldApiBinary:
        result.step_failed = 1
        result.error_message = "test_gldapi binary not found"
        return result
    
    # Get the test working directory
    testDir = testFile.parent / testFile.stem
    testDir.resolve()
    testFileName = testFile.name
    run_env = build_gld_environment()
    cleanup_test_artifacts(testDir, testFile.stem)
    
    try:
        # Step 1: Baseline run
        print(f"[{testFile.name}] Step 1/4: Baseline run...", end=" ", flush=True)
        step1_command = [testGldApiBinary, testFileName]
        step1_result = run_process(step1_command, testDir, run_env, 300, verbose)
        
        if step1_result.returncode != 0:
            if not verbose:
                step1_result = run_process(step1_command, testDir, run_env, 300, True)
            result.step_failed = 1
            result.error_message = "Baseline run failed"
            result.details['step_1'] = (step1_result.stdout or "") + (step1_result.stderr or "")
            print("FAILED")
            return result
        print("OK")
        
        # Step 2: Partial run with checkpoint (1 timestep)
        print(f"[{testFile.name}] Step 2/4: Checkpoint at 1 timestep...", end=" ", flush=True)
        step2_command = [testGldApiBinary, testFileName, "--checkpoint", "--steps", "1"]
        step2_result = run_process(step2_command, testDir, run_env, 300, verbose)
        
        if step2_result.returncode != 0:
            if not verbose:
                step2_result = run_process(step2_command, testDir, run_env, 300, True)
            result.step_failed = 2
            result.error_message = "Checkpoint creation failed"
            result.details['step_2'] = (step2_result.stdout or "") + (step2_result.stderr or "")
            print("FAILED")
            return result
        print("OK")
        
        # Step 3: Restore from checkpoint
        print(f"[{testFile.name}] Step 3/4: Restore from checkpoint...", end=" ", flush=True)
        step3_command = [testGldApiBinary, testFileName, "--restore"]
        step3_result = run_process(step3_command, testDir, run_env, 300, verbose)
        
        if step3_result.returncode != 0:
            if not verbose:
                step3_result = run_process(step3_command, testDir, run_env, 300, True)
            result.step_failed = 3
            result.error_message = "Checkpoint restore failed"
            result.details['step_3'] = (step3_result.stdout or "") + (step3_result.stderr or "")
            print("FAILED")
            return result
        print("OK")
        
        # Step 4: Compare results
        print(f"[{testFile.name}] Step 4/4: Compare results...", end=" ", flush=True)
        step4_command = [testGldApiBinary, testFileName, "--compare", "--tolerance", ".00006"]
        step4_result = run_process(step4_command, testDir, run_env, 300, True)
        
        # Parse comparison output to count differences
        compare_output = (step4_result.stdout or "") + (step4_result.stderr or "")
        difference_count = parse_difference_count(compare_output, step4_result.returncode)
        result.differences = difference_count
        
        if step4_result.returncode != 0 and difference_count is None:
            result.step_failed = 4
            result.error_message = "Comparison failed"
            result.details['step_4'] = compare_output
            print("FAILED")
            return result
        print("OK")
        
        # Step 4 completed - report differences found
        if result.differences is not None:
            if result.differences == 0:
                print(f"[{testFile.name}] No differences found ✓")
            else:
                print(f"[{testFile.name}] Found {result.differences} differences")
        if not keepCheckpoints:
            cleanup_test_artifacts(testDir, testFile.stem)
        return result
        
    except subprocess.TimeoutExpired:
        result.step_failed = result.step_failed if result.step_failed else 1
        result.error_message = "Timeout exceeded (300s)"
        print(f"TIMEOUT")
        return result
    except Exception as e:
        result.step_failed = result.step_failed if result.step_failed else 1
        result.error_message = f"Exception: {str(e)}"
        print(f"ERROR: {str(e)}")
        return result

def getGLDVersionInfo() -> str:
    """
    Get the GridLAB-D version information.
    """
    try:
        command = [testGldApiBinary, "--version"]
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except:
        pass
    return "Unknown GridLAB-D version"

def processResults(results: list, resultsFile: Path, testPerformance: int, keepCheckpoints: bool) -> int:
    """
    Process the results and output to checkpoint_results.txt
    """
    global autotestFiles
    rv = 0
    gldInfo = getGLDVersionInfo()
    
    # Categorize results
    skipped_tests = []      # DELTAMODE-enabled/ERRor tests/explicit skips not run
    perfect_tests = []      # 0 differences
    acceptable_tests = []   # > 0 differences but completed
    failed_tests = []       # Didn't complete checkpoint process
    
    for result in results:
        if result.skipped:
            skipped_tests.append(result)
        elif result.step_failed:
            failed_tests.append(result)
        elif result.differences == 0:
            perfect_tests.append(result)
        elif result.differences is not None and result.differences > 0:
            acceptable_tests.append(result)
        else:
            failed_tests.append(result)
    
    # Sort acceptable tests by difference count (descending)
    acceptable_tests.sort(key=lambda r: r.differences if r.differences else 0, reverse=True)
    
    with resultsFile.open("w") as f:
        f.write(f"GridLAB-D Checkpoint Validation Results\n")
        f.write(f"{'='*60}\n\n")
        f.write(f"GridLAB-D Version Info:\n\t{gldInfo}\n\n")
        f.write("Checkpoint Test Results by Category:\n\n")
        
        # Perfect tests (0 differences)
        if skipped_tests:
            f.write(f"- Skipped (DELTAMODE/ERR/Exclude) - {len(skipped_tests)} tests:\n")
            for result in skipped_tests:
                f.write(f"\t{result}\n")
            f.write("\n")

        if perfect_tests:
            f.write(f"✓ Perfect Match (0 differences) - {len(perfect_tests)} tests:\n")
            for result in perfect_tests:
                f.write(f"\t{result}\n")
            f.write("\n")
        
        # Acceptable tests (differences but completed)
        if acceptable_tests:
            f.write(f"≈ Acceptable (with differences) - {len(acceptable_tests)} tests:\n")
            for result in acceptable_tests:
                f.write(f"\t{result}\n")
            f.write("\n")
        
        # Failed tests
        if failed_tests:
            f.write(f"✗ Failed (incomplete) - {len(failed_tests)} tests:\n")
            for result in failed_tests:
                f.write(f"\t{result}\n")
            f.write("\n")
        
        f.write(f"\n{'='*60}\n")
        f.write("Results Summary:\n")
        total_tests_discovered = len(results)
        total_tests_run = total_tests_discovered - len(skipped_tests)
        f.write(f"\tTotal Tests Discovered: {total_tests_discovered}\n")
        f.write(f"\tTotal Tests Run: {total_tests_run}\n")
        f.write(f"\tSkipped (DELTAMODE/ERR/Exclude): {len(skipped_tests)}\n")
        f.write(f"\tPerfect (0 diff): {len(perfect_tests)}\n")
        f.write(f"\tAcceptable (>0 diff): {len(acceptable_tests)}\n")
        f.write(f"\tFailed (incomplete): {len(failed_tests)}\n")
        
        total_completed = len(perfect_tests) + len(acceptable_tests)
        if total_tests_run > 0:
            f.write(f"\tCompleted Rate: {math.floor((float(total_completed) / float(total_tests_run)) * 100.0)}%\n")
        if acceptable_tests:
            total_diffs = sum(r.differences for r in acceptable_tests if r.differences)
            avg_diffs = total_diffs / len(acceptable_tests) if acceptable_tests else 0
            max_diffs = max(r.differences for r in acceptable_tests if r.differences)
            f.write(f"\tMax Differences: {max_diffs}\n")
            f.write(f"\tAvg Differences (acceptable tests): {avg_diffs:.1f}\n")
        f.write(f"\tTotal Test Time: {testPerformance} seconds\n")
        
        # Details on failures
        if failed_tests:
            f.write(f"\n{'='*60}\n")
            f.write("Failed Tests Details:\n\n")
            for result in failed_tests:
                f.write(f"{result.test_file.stem}:\n")
                if result.step_failed:
                    f.write(f"  Failed at Step: {result.step_failed}\n")
                if result.error_message:
                    f.write(f"  Error: {result.error_message}\n")
                f.write("\n")
        
        # Details on acceptable tests with high differences
        if acceptable_tests and any(r.differences and r.differences > 10 for r in acceptable_tests):
            f.write(f"\n{'='*60}\n")
            f.write("Tests with High Differences (>10):\n\n")
            for result in acceptable_tests:
                if result.differences and result.differences > 10:
                    f.write(f"  {result.test_file.stem}: {result.differences} differences\n")
    
    # Print summary to console
    print("\n" + "="*60)
    print("Checkpoint Testing Summary:")
    total_tests_discovered = len(results)
    total_tests_run = total_tests_discovered - len(skipped_tests)
    print(f"  Total Tests Discovered: {total_tests_discovered}")
    print(f"  Total Tests Run: {total_tests_run}")
    print(f"  - Skipped (DELTAMODE/ERR/Exclude): {len(skipped_tests)}")
    print(f"  ✓ Perfect (0 differences): {len(perfect_tests)}")
    print(f"  ≈ Acceptable (with differences): {len(acceptable_tests)}")
    print(f"  ✗ Failed (incomplete): {len(failed_tests)}")
    total_completed = len(perfect_tests) + len(acceptable_tests)
    if total_tests_run > 0:
        print(f"  Completed Rate: {math.floor((float(total_completed) / float(total_tests_run)) * 100.0)}%")
    if acceptable_tests:
        max_diffs = max(r.differences for r in acceptable_tests if r.differences)
        print(f"  Max Differences: {max_diffs}")
    print(f"  Total Test Time: {testPerformance} seconds")
    print(f"  Results written to: {resultsFile}")
    print("="*60 + "\n")
    
    # Return non-zero if any tests failed to complete
    if failed_tests:
        rv = 1
    
    return rv

def main(module: str, runOptionalTests: bool, threads: int, keepCheckpoints: bool, verbose: bool):
    global autotestFiles
    rv = 0
    
    multiprocessing.set_start_method("spawn", force=True)
    procs = 1
    if threads < 1:
        procs = multiprocessing.cpu_count()
    else:
        procs = min(threads, multiprocessing.cpu_count())
    
    getTestGldApiBinary()
    
    searchDirectoryBase = Path(__file__).parent.resolve()
    moduleDirectory = None
    resultsFile = searchDirectoryBase / "checkpoint_results.txt"
    resultsFile.resolve()
    
    if resultsFile.exists():
        resultsFile.unlink()
    
    print(f"GridLAB-D Checkpoint Validation")
    print(f"{'='*60}")
    print(f"Using test_gldapi binary: {testGldApiBinary}")
    print(f"Parallel threads: {procs}")
    if module != "all":
        print(f"Module: {module}")
    print(f"{'='*60}\n")
    
    # Search for autotest files
    if module != "all":
        moduleDirectory = searchDirectoryBase / module
        moduleDirectory.resolve()
        if not moduleDirectory.exists() or not moduleDirectory.is_dir():
            raise IOError(f"The module, {module}, does not exist.")
        processModuleDirectory(moduleDirectory, runOptionalTests)
    else:
        for moduleChild in searchDirectoryBase.iterdir():
            if moduleChild.is_dir() and not moduleChild.name.startswith('.'):
                # Skip common non-module directories
                skip_dirs = ['build', 'bin', '.venv', 'node_modules', '_test_results']
                if moduleChild.name not in skip_dirs:
                    processModuleDirectory(moduleChild.resolve(), runOptionalTests)
    
    # Run checkpoint tests in parallel
    autotestFiles.sort(key=lambda x: str(x))
    
    if len(autotestFiles) > 0:
        procs = min(procs, len(autotestFiles))
        print(f"Discovered {len(autotestFiles)} test files\n")
        print(f"{'='*60}")
        print("Starting checkpoint tests...\n")
        
        results = []
        startTime = time.perf_counter()
        
        run_args = [(test_file, keepCheckpoints, verbose) for test_file in autotestFiles]
        with multiprocessing.Pool(procs) as p:
            results = p.starmap(runCheckpointTest, run_args)
        
        endTime = time.perf_counter()
        testPerformance = math.ceil(endTime - startTime)
        
        print(f"\n{'='*60}")
        rv = processResults(results, resultsFile, testPerformance, keepCheckpoints)
        
    elif module != "all":
        print(f"No autotest files were found recursively searching from {moduleDirectory}. Exiting.")
    else:
        print(f"No autotest files were found recursively searching from {searchDirectoryBase}. Exiting.")
    
    if rv == 1:
        sys.exit(1)

if __name__ == "__main__":
    parser = ArgumentParser(description="Validate GridLAB-D checkpoint functionality by running autotests through a 4-step checkpoint process.")
    parser.add_argument(
        "-m",
        "--module",
        type=str,
        default="all",
        help="The specific module to validate. Default is all modules."
    )
    parser.add_argument(
        "-t",
        "--threads",
        type=int,
        default=0,
        help="Number of parallel threads (0 = CPU count, default)."
    )
    parser.add_argument(
        "-o",
        "--run_optional_tests",
        action="store_true",
        help="Run optional tests (those with _opt suffix) as well."
    )
    parser.add_argument(
        "--keep-checkpoints",
        action="store_true",
        help="Keep checkpoint files after testing (default: delete)."
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print detailed output for each test."
    )
    
    args = parser.parse_args()
    
    try:
        main(
            module=args.module,
            runOptionalTests=args.run_optional_tests,
            threads=args.threads,
            keepCheckpoints=args.keep_checkpoints,
            verbose=args.verbose
        )
    except ModuleNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except IOError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nValidation interrupted by user.", file=sys.stderr)
        sys.exit(130)
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        sys.exit(1)
