#if !defined(__ODBCXX_SETUP_H)
# error "Do not include this file directly. Use <odbc++/setup.h> instead"
#endif
/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Defined if threads enabled */
/* #undef ODBCXX_ENABLE_THREADS */

/* Define to 1 if you have the <cstdio> header file. */
#define ODBCXX_HAVE_CSTDIO 1

/* Define to 1 if you have the <cstdlib> header file. */
#define ODBCXX_HAVE_CSTDLIB 1

/* Define to 1 if you have the <cstring> header file. */
#define ODBCXX_HAVE_CSTRING 1

/* Define to 1 if you have the <ctime> header file. */
#define ODBCXX_HAVE_CTIME 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define ODBCXX_HAVE_DLFCN_H 1

/* Define to 1 if you have the <exception> header file. */
#define ODBCXX_HAVE_EXCEPTION 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define ODBCXX_HAVE_INTTYPES_H 1

/* Define to 1 if you have the <iostream> header file. */
#define ODBCXX_HAVE_IOSTREAM 1

/* Define to 1 if you have the <iostream.h> header file. */
#define ODBCXX_HAVE_IOSTREAM_H 1

/* Defined if using iodbc */
/* #undef ODBCXX_HAVE_ISQLEXT_H */

/* Defined if using iodbc */
/* #undef ODBCXX_HAVE_ISQL_H */

/* Define to 1 if you have the <istream> header file. */
#define ODBCXX_HAVE_ISTREAM 1

/* Defined if using iodbc */
/* #undef ODBCXX_HAVE_LIBIODBC */

/* defined if using unixodbc */
#define ODBCXX_HAVE_LIBODBC 

/* Define to 1 if you have the `localtime_r' function. */
/* #undef ODBCXX_HAVE_LOCALTIME_R */

/* Define if we have long long */
#define ODBCXX_HAVE_LONG_LONG 1

/* Define to 1 if you have the <memory.h> header file. */
#define ODBCXX_HAVE_MEMORY_H 1

/* Define to 1 if you have the `pthread_create' function. */
/* #undef ODBCXX_HAVE_PTHREAD_CREATE */

/* Defined if pthreads are available */
/* #undef ODBCXX_HAVE_PTHREAD_H */

/* Define to 1 if you have the <readline/history.h> header file. */
/* #undef ODBCXX_HAVE_READLINE_HISTORY_H */

/* Define to 1 if you have the <readline/readline.h> header file. */
/* #undef ODBCXX_HAVE_READLINE_READLINE_H */

/* Define to 1 if you have the <set> header file. */
#define ODBCXX_HAVE_SET 1

/* Define to 1 if you have the <set.h> header file. */
#define ODBCXX_HAVE_SET_H 1

/* Define to 1 if you have the `snprintf' function. */
#define ODBCXX_HAVE_SNPRINTF 1

/* Define to 1 if you have the <sqlext.h> header file. */
#define ODBCXX_HAVE_SQLEXT_H 1

/* Define to 1 if you have the <sqlucode.h> header file. */
#define ODBCXX_HAVE_SQLUCODE_H 1

/* Define to 1 if you have the <sql.h> header file. */
#define ODBCXX_HAVE_SQL_H 1

/* Define to 1 if you have the <sstream> header file. */
#define ODBCXX_HAVE_SSTREAM 1

/* Define to 1 if you have the <stdint.h> header file. */
#define ODBCXX_HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define ODBCXX_HAVE_STDLIB_H 1

/* Define to 1 if you have the <string> header file. */
#define ODBCXX_HAVE_STRING 1

/* Define to 1 if you have the <strings.h> header file. */
#define ODBCXX_HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define ODBCXX_HAVE_STRING_H 1

/* Define to 1 if you have the <strstream> header file. */
#define ODBCXX_HAVE_STRSTREAM 1

/* Define to 1 if you have the <strstream.h> header file. */
#define ODBCXX_HAVE_STRSTREAM_H 1

/* Define to 1 if you have the `strtoll' function. */
#define ODBCXX_HAVE_STRTOLL 1

/* Define to 1 if you have the `strtoq' function. */
#define ODBCXX_HAVE_STRTOQ 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define ODBCXX_HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define ODBCXX_HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define ODBCXX_HAVE_UNISTD_H 1

/* Define to 1 if you have the <vector> header file. */
#define ODBCXX_HAVE_VECTOR 1

/* Define to 1 if you have the <vector.h> header file. */
#define ODBCXX_HAVE_VECTOR_H 1

/* ODBC version */
/* #undef ODBCXX_ODBCVER */

/* Name of package */
#define ODBCXX_PACKAGE ""

/* Define to the address where bug reports for this package should be sent. */
#define ODBCXX_PACKAGE_BUGREPORT "libodbcxx-devel@lists.sourceforge.net"

/* Define to the full name of this package. */
#define ODBCXX_PACKAGE_NAME "libodbcxx"

/* Define to the full name and version of this package. */
#define ODBCXX_PACKAGE_STRING "libodbcxx 0.2.4pre1"

/* Define to the one symbol short name of this package. */
#define ODBCXX_PACKAGE_TARNAME "libodbc++"

/* Define to the version of this package. */
#define ODBCXX_PACKAGE_VERSION "0.2.4pre1"

/* The size of a `int', as computed by sizeof. */
#define ODBCXX_SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define ODBCXX_SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define ODBCXX_SIZEOF_LONG_LONG 8

/* Define to 1 if you have the ANSI C header files. */
#define ODBCXX_STDC_HEADERS 1

/* Version number of package */
#define ODBCXX_VERSION ""
