CREATE TABLE IF NOT EXISTS `test.csv` (
	`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`t` DATETIME NOT NULL,
	`x[min]` DOUBLE
);

LOAD DATA LOCAL INFILE '../test_mysql_player.csv' 
INTO TABLE `test.csv`
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(id, t,`x[min]`);