stream_type(double);
stream_type(complex);
stream_type(enumeration);
stream_type(set);
stream_type(int16);
stream_type(int32);
stream_type(int64);
stream_type(char8);
stream_type(char32);
stream_type(char256);
stream_type(char1024);
stream_type(object);
stream_type(bool);
stream_type(TIMESTAMP);
stream_type(double_array);
stream_type(complex_array);
stream_type(float);
stream_type(real);
stream_type(loadshape);
stream_type(enduse);
stream_type(randomvar);

stream_type(TOKEN);
stream_type(uint);
stream_type(uchar);
stream_type(uint16);
stream_type(uint32);
stream_type(uint64);

