/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gridlabd_GridlabD */

#ifndef _Included_gridlabd_GridlabD
#define _Included_gridlabd_GridlabD
#ifdef __cplusplus
extern "C" {
#endif
#undef gridlabd_GridlabD_TS_NEVER
#define gridlabd_GridlabD_TS_NEVER 9223372036854775807i64
#undef gridlabd_GridlabD_TS_INVALID
#define gridlabd_GridlabD_TS_INVALID -1i64
#undef gridlabd_GridlabD_TS_ZERO
#define gridlabd_GridlabD_TS_ZERO 0i64
#undef gridlabd_GridlabD_TS_MAX
#define gridlabd_GridlabD_TS_MAX 9223372036854775807i64
#undef gridlabd_GridlabD_MINYEAR
#define gridlabd_GridlabD_MINYEAR 1970i64
#undef gridlabd_GridlabD_MAXYEAR
#define gridlabd_GridlabD_MAXYEAR 2969i64
#undef gridlabd_GridlabD_PC_NOSYNC
#define gridlabd_GridlabD_PC_NOSYNC 0L
#undef gridlabd_GridlabD_PC_PRETOPDOWN
#define gridlabd_GridlabD_PC_PRETOPDOWN 1L
#undef gridlabd_GridlabD_PC_BOTTOMUP
#define gridlabd_GridlabD_PC_BOTTOMUP 2L
#undef gridlabd_GridlabD_PC_POSTTOPDOWN
#define gridlabd_GridlabD_PC_POSTTOPDOWN 4L
#undef gridlabd_GridlabD_PI
#define gridlabd_GridlabD_PI 3.141592653589793
#undef gridlabd_GridlabD_E
#define gridlabd_GridlabD_E 2.71828182845905
#undef gridlabd_GridlabD_NM_PREUPDATE
#define gridlabd_GridlabD_NM_PREUPDATE 0L
#undef gridlabd_GridlabD_NM_POSTUPDATE
#define gridlabd_GridlabD_NM_POSTUPDATE 1L
#undef gridlabd_GridlabD_NM_RESET
#define gridlabd_GridlabD_NM_RESET 2L
#undef gridlabd_GridlabD_OF_NONE
#define gridlabd_GridlabD_OF_NONE 0L
#undef gridlabd_GridlabD_OF_HASPLC
#define gridlabd_GridlabD_OF_HASPLC 1L
#undef gridlabd_GridlabD_OF_LOCKED
#define gridlabd_GridlabD_OF_LOCKED 2L
/*
 * Class:     gridlabd_GridlabD
 * Method:    GetInt16
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_GetInt16
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    GetInt32
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_GetInt32
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    GetInt64
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_GetInt64
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    GetDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_GetDouble
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    GetComplex
 * Signature: (JJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_gridlabd_GridlabD_GetComplex
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    SetInt16
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_SetInt16
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     gridlabd_GridlabD
 * Method:    SetInt32
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_SetInt32
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     gridlabd_GridlabD
 * Method:    SetInt64
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_SetInt64
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    SetDouble
 * Signature: (JJD)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_SetDouble
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    SetComplex
 * Signature: (JJDD)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_SetComplex
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    verbose
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_verbose
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    output
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_output
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    warning
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_warning
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    error
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_error
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    debug
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_debug
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    testmsg
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_testmsg
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_module_var
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_get_1module_1var
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    findfile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gridlabd_GridlabD_findfile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    find_module
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_find_1module
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    register_class
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_register_1class
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     gridlabd_GridlabD
 * Method:    create_object
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_create_1object
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    create_array
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_create_1array
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     gridlabd_GridlabD
 * Method:    object_isa
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_object_1isa
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    publish_variable
 * Signature: (JJLjava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_publish_1variable
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    publish_function
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_publish_1function
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    set_dependent
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_set_1dependent
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    set_parent
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_set_1parent
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    register_type
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_register_1type
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    publish_delegate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_publish_1delegate
  (JNIEnv *, jclass);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_property
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_get_1property
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_property_by_name
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_get_1property_1by_1name
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_value
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gridlabd_GridlabD_get_1value
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    set_value
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_set_1value
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    unit_convert
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_unit_1convert
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_complex_real
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_get_1complex_1real
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_complex_imag
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_get_1complex_1imag
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_complex_real_by_name
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_get_1complex_1real_1by_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_complex_imag_by_name
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_get_1complex_1imag_1by_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_object
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_get_1object
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_int16
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_get_1int16
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_int16_by_name
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_get_1int16_1by_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_int32
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_get_1int32
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_int32_by_name
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_get_1int32_1by_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_int64
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_get_1int64
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_int64_by_name
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_get_1int64_1by_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_double
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_get_1double
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_double_by_name
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_get_1double_1by_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_string
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gridlabd_GridlabD_get_1string
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    get_string_by_name
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gridlabd_GridlabD_get_1string_1by_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    find_objects
 * Signature: (J[Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_gridlabd_GridlabD_find_1objects
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     gridlabd_GridlabD
 * Method:    find_next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_find_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    create_aggregate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_create_1aggregate
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    run_aggregate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_run_1aggregate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    random_uniform
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_random_1uniform
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    random_normal
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_random_1normal
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    random_lognormal
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_random_1lognormal
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    random_bernoulli
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_random_1bernoulli
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    random_pareto
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_random_1pareto
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    random_sampled
 * Signature: (I[D)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_random_1sampled
  (JNIEnv *, jclass, jint, jdoubleArray);

/*
 * Class:     gridlabd_GridlabD
 * Method:    random_exponential
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_random_1exponential
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     gridlabd_GridlabD
 * Method:    parsetime
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_parsetime
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    strtime
 * Signature: (Ljava/lang/Object;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_strtime
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     gridlabd_GridlabD
 * Method:    todays
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_todays
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    tohours
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_tohours
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    tominutes
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_gridlabd_GridlabD_tominutes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gridlabd_GridlabD
 * Method:    localtime
 * Signature: (JLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_localtime
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gridlabd_GridlabD
 * Method:    global_create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_global_1create
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    global_setvar
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gridlabd_GridlabD_global_1setvar
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    global_getvar
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gridlabd_GridlabD_global_1getvar
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gridlabd_GridlabD
 * Method:    global_find
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gridlabd_GridlabD_global_1find
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
